/**
 * File: adapters/integrations/azure-devops/src/index.ts
 * Purpose: Implements Azure DevOps commit-status, work-item, comment, and build-trigger integration through REST and secret references.
 * Author: Raushan Raj
 */
import type { AdapterHealth,IntegrationAdapter,IntegrationRequest,IntegrationResponse,NetworkPolicy,SecretReference } from '../../../../packages/contracts/src';
import type { SecretResolverRegistry } from '../../../../packages/security/src/secrets';
import { assertNetworkAllowed } from '../../../../packages/security/src/network-policy';
import { asIntegrationRecord,FetchIntegrationHttpTransport,type IntegrationHttpTransport } from '../../../../packages/integrations/src/http';
import { dedupe,InMemoryIntegrationDedupeStore,type IntegrationDedupeStore } from '../../../../packages/integrations/src/dedupe';
import { withIntegrationRetry,type IntegrationRetryPolicy } from '../../../../packages/integrations/src/retry';
import { basicHeader,bearerHeader,encodeSegment,endpoint,normalizeStatus,optionalString,rateLimit,requiredNumber,requiredString } from '../../../../packages/integrations/src/utils';

export interface AzureDevOpsIntegrationOptions{id?:string;baseUrl:string;organization:string;project:string;credential:SecretReference;authMode:'bearer'|'pat';username?:string;secrets:SecretResolverRegistry;networkPolicy:NetworkPolicy;transport?:IntegrationHttpTransport;timeoutMs?:number;headers?:Record<string,string>;retryPolicy?:IntegrationRetryPolicy;dedupeStore?:IntegrationDedupeStore;}
export class AzureDevOpsIntegrationAdapter implements IntegrationAdapter{
  readonly descriptor;private readonly transport;private readonly dedupeStore;
  constructor(private readonly options:AzureDevOpsIntegrationOptions){this.descriptor={id:options.id??'azure-devops',kind:'integration' as const,version:'1.0.0',displayName:'Azure DevOps',description:'Azure DevOps Git status, work item, comment, and build integration',capabilities:['publish-status','create-work-item','comment','trigger-build'],supportedTools:['azure-devops']};this.transport=options.transport??new FetchIntegrationHttpTransport();this.dedupeStore=options.dedupeStore??new InMemoryIntegrationDedupeStore();}
  async health():Promise<AdapterHealth>{try{const url=endpoint(this.options.baseUrl,`${encodeSegment(this.options.organization)}/${encodeSegment(this.options.project)}`);assertNetworkAllowed(url,this.options.networkPolicy);return{status:'healthy',message:'configured; no remote health request performed',checkedAt:new Date().toISOString()};}catch(error){return{status:'unavailable',message:error instanceof Error?error.message:'invalid configuration',checkedAt:new Date().toISOString()};}}
  async execute(request:IntegrationRequest):Promise<IntegrationResponse>{switch(request.operation){case'publish-status':return this.publishStatus(request);case'create-work-item':return this.createWorkItem(request);case'comment':return this.comment(request);case'trigger-build':return this.triggerBuild(request);default:throw new Error(`Azure DevOps integration does not support operation: ${request.operation}`);}}
  private async publishStatus(request:IntegrationRequest){const repositoryId=requiredString(request.payload,'repositoryId');const commitId=requiredString(request.payload,'commitId');const state=normalizeStatus(request.payload.state??request.payload.status);const adoState=state==='success'?'succeeded':state==='failure'?'failed':state==='pending'?'pending':state==='error'?'error':'notSet';const body={state:adoState,description:optionalString(request.payload,'description'),targetUrl:optionalString(request.payload,'targetUrl'),context:{name:optionalString(request.payload,'context')??'Qualyntra',genre:optionalString(request.payload,'genre')??'quality-engineering'}};return this.post(request,`${this.basePath()}/_apis/git/repositories/${encodeSegment(repositoryId)}/commits/${encodeSegment(commitId)}/statuses?api-version=7.1`,body,'application/json',request.idempotencyKey);}
  private async createWorkItem(request:IntegrationRequest){if(!request.idempotencyKey)throw new Error('Azure DevOps create-work-item requires idempotencyKey to prevent duplicate work items');const type=requiredString(request.payload,'type');const title=requiredString(request.payload,'title');const description=optionalString(request.payload,'description');const fields=request.payload.fields&&typeof request.payload.fields==='object'?request.payload.fields as Record<string,unknown>:{};const patch:any[]=[{op:'add',path:'/fields/System.Title',value:title}];if(description)patch.push({op:'add',path:'/fields/System.Description',value:description});for(const [name,value] of Object.entries(fields))patch.push({op:'add',path:`/fields/${name}`,value});return this.post(request,`${this.basePath()}/_apis/wit/workitems/$${encodeSegment(type)}?api-version=7.1`,patch,'application/json-patch+json',request.idempotencyKey);}
  private async comment(request:IntegrationRequest){const workItemId=requiredNumber(request.payload,'workItemId');const text=requiredString(request.payload,'text');return this.post(request,`${this.basePath()}/_apis/wit/workItems/${workItemId}/comments?format=Markdown&api-version=7.1-preview.4`,{text},'application/json',request.idempotencyKey);}
  private async triggerBuild(request:IntegrationRequest){if(!request.idempotencyKey)throw new Error('Azure DevOps trigger-build requires idempotencyKey to prevent duplicate builds');const definitionId=requiredNumber(request.payload,'definitionId');const body:any={definition:{id:definitionId}};const sourceBranch=optionalString(request.payload,'sourceBranch');if(sourceBranch)body.sourceBranch=sourceBranch;if(request.payload.parameters&&typeof request.payload.parameters==='object')body.templateParameters=request.payload.parameters;return this.post(request,`${this.basePath()}/_apis/build/builds?api-version=7.1`,body,'application/json',request.idempotencyKey);}
  private basePath(){return`${encodeSegment(this.options.organization)}/${encodeSegment(this.options.project)}`;}
  private async auth(){return this.options.authMode==='bearer'?bearerHeader(this.options.secrets,this.options.credential):basicHeader(this.options.secrets,this.options.credential,this.options.username??'');}
  private async post(request:IntegrationRequest,path:string,body:unknown,contentType:string,dedupeKey?:string):Promise<IntegrationResponse>{const key=dedupeKey?`${this.descriptor.id}:${request.scope.organizationId}:${request.operation}:${dedupeKey}`:undefined;return dedupe(this.dedupeStore,key,async()=>withIntegrationRetry(async()=>{const url=endpoint(this.options.baseUrl,path);assertNetworkAllowed(url,this.options.networkPolicy);const response=await this.transport.request({adapterId:this.descriptor.id,url,method:'POST',headers:{accept:'application/json','content-type':contentType,authorization:await this.auth(),...this.options.headers},body:JSON.stringify(body),timeoutMs:this.options.timeoutMs});const value=asIntegrationRecord(response.body);const id=value.id??value.commentId;return{ok:true,externalId:id===undefined?undefined:String(id),uri:typeof value.url==='string'?value.url:typeof value._links?.html?.href==='string'?value._links.html.href:undefined,requestId:response.headers['x-vss-e2eid']??response.headers['x-request-id'],rateLimit:rateLimit(response.headers),metadata:{status:response.status}};},{idempotent:Boolean(dedupeKey),policy:this.options.retryPolicy}));}
}
