/**
 * File: adapters/persistence/postgres/src/distributed-queue.ts
 * Purpose: Implements the durable distributed execution queue and worker registry on PostgreSQL with transactional leases and SKIP LOCKED scheduling.
 * Author: Raushan Raj
 */
import type { DistributedExecutionJob,DistributedExecutionQueue,DistributedQueueHealth,LeaseOptions,WorkerRegistration,WorkerState } from '../../../../packages/contracts/src/distributed';
import type { ExecutionResult } from '../../../../packages/contracts/src/execution';
import { createId } from '../../../../packages/core/src/ids';
import { workerMatches } from '../../../../packages/distributed/src/matching';
import type { PostgresDatabase,PostgresQueryExecutor,PostgresTransaction } from './driver';
import { restoredScope,storedScope } from './scope';

function json<T>(value:unknown):T{return(typeof value==='string'?JSON.parse(value):value) as T;}
function iso(value:unknown):string{return new Date(value as any).toISOString();}
function later(now:string,ms:number):string{return new Date(Date.parse(now)+ms).toISOString();}
function terminal(state:string):boolean{return['succeeded','failed','cancelled','dead-letter'].includes(state);}
function workerFrom(row:any):WorkerRegistration{return{id:String(row.id),scope:restoredScope(row),capabilities:json(row.capabilities_json),maxConcurrency:Number(row.max_concurrency),state:row.state,registeredAt:iso(row.registered_at),heartbeatAt:iso(row.heartbeat_at),activeLeases:Number(row.active_leases),metadata:row.metadata_json?json(row.metadata_json):undefined};}
function jobFrom(row:any):DistributedExecutionJob{const job:DistributedExecutionJob={id:String(row.id),runId:String(row.run_id),scope:restoredScope(row),request:json(row.request_json),requirements:json(row.requirements_json),state:row.state,attempt:Number(row.attempt),maxAttempts:Number(row.max_attempts),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),availableAt:iso(row.available_at),metadata:row.metadata_json?json(row.metadata_json):undefined};if(row.lease_id)job.lease={id:String(row.lease_id),workerId:String(row.lease_worker_id),acquiredAt:iso(row.lease_acquired_at),heartbeatAt:iso(row.lease_heartbeat_at),expiresAt:iso(row.lease_expires_at)};if(row.result_json)job.result=json(row.result_json);if(row.failure_json)job.failure=json(row.failure_json);return job;}
async function lockedJob(tx:PostgresTransaction,id:string):Promise<DistributedExecutionJob>{const result=await tx.query<any>('SELECT * FROM qualyntra_distributed_jobs WHERE id=$1 FOR UPDATE',[id]);if(!result.rows[0])throw new Error(`Distributed job not found: ${id}`);return jobFrom(result.rows[0]);}
function assertActiveLease(job:DistributedExecutionJob,leaseId:string,now:string):void{if(!job.lease||job.lease.id!==leaseId)throw new Error(`Lease mismatch for job: ${job.id}`);if(Date.parse(now)>Date.parse(job.lease.expiresAt))throw new Error(`Lease expired for job: ${job.id}`);}
async function releaseWorker(tx:PostgresTransaction,workerId:string):Promise<void>{await tx.query('UPDATE qualyntra_workers SET active_leases=GREATEST(active_leases-1,0) WHERE id=$1',[workerId]);}

export class PostgresDistributedExecutionQueue implements DistributedExecutionQueue{
  constructor(private readonly database:PostgresDatabase,private readonly candidateBatchSize=100){if(!Number.isInteger(candidateBatchSize)||candidateBatchSize<1||candidateBatchSize>1000)throw new Error('candidateBatchSize must be between 1 and 1000.');}
  async enqueue(job:DistributedExecutionJob):Promise<DistributedExecutionJob>{const s=storedScope(job.scope);await this.database.query('INSERT INTO qualyntra_distributed_jobs (id,run_id,organization_id,workspace_id,project_id,environment_id,request_json,requirements_json,state,attempt,max_attempts,created_at,updated_at,available_at,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,$11,$12,$13,$14,$15::jsonb)',[job.id,job.runId,s.organizationId,s.workspaceId,s.projectId,s.environmentId,JSON.stringify(job.request),JSON.stringify(job.requirements),job.state,job.attempt,job.maxAttempts,job.createdAt,job.updatedAt,job.availableAt,JSON.stringify(job.metadata??{})]);return structuredClone(job);}
  async getJob(id:string):Promise<DistributedExecutionJob|undefined>{const result=await this.database.query<any>('SELECT * FROM qualyntra_distributed_jobs WHERE id=$1 LIMIT 1',[id]);return result.rows[0]?jobFrom(result.rows[0]):undefined;}
  async cancel(id:string,now:string):Promise<DistributedExecutionJob>{return this.database.transaction(async tx=>{const job=await lockedJob(tx,id);if(terminal(job.state))return job;if(job.lease)await releaseWorker(tx,job.lease.workerId);const result=await tx.query<any>("UPDATE qualyntra_distributed_jobs SET state='cancelled',updated_at=$2,lease_id=NULL,lease_worker_id=NULL,lease_acquired_at=NULL,lease_heartbeat_at=NULL,lease_expires_at=NULL WHERE id=$1 RETURNING *",[id,now]);return jobFrom(result.rows[0]);});}
  async registerWorker(worker:WorkerRegistration):Promise<WorkerRegistration>{if(!Number.isInteger(worker.maxConcurrency)||worker.maxConcurrency<1)throw new Error('Worker maxConcurrency must be a positive integer.');const s=storedScope(worker.scope);const result=await this.database.query<any>('INSERT INTO qualyntra_workers (id,organization_id,workspace_id,project_id,environment_id,capabilities_json,max_concurrency,state,registered_at,heartbeat_at,active_leases,metadata_json) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,0,$11::jsonb) ON CONFLICT (id) DO UPDATE SET capabilities_json=EXCLUDED.capabilities_json,max_concurrency=EXCLUDED.max_concurrency,state=EXCLUDED.state,heartbeat_at=EXCLUDED.heartbeat_at,metadata_json=EXCLUDED.metadata_json WHERE qualyntra_workers.organization_id=EXCLUDED.organization_id AND qualyntra_workers.workspace_id=EXCLUDED.workspace_id AND qualyntra_workers.project_id=EXCLUDED.project_id AND qualyntra_workers.environment_id=EXCLUDED.environment_id RETURNING *',[worker.id,s.organizationId,s.workspaceId,s.projectId,s.environmentId,JSON.stringify(worker.capabilities),worker.maxConcurrency,worker.state,worker.registeredAt,worker.heartbeatAt,JSON.stringify(worker.metadata??{})]);if(!result.rows[0])throw new Error(`Worker registration scope conflict: ${worker.id}`);return workerFrom(result.rows[0]);}
  async getWorker(id:string):Promise<WorkerRegistration|undefined>{const result=await this.database.query<any>('SELECT * FROM qualyntra_workers WHERE id=$1 LIMIT 1',[id]);return result.rows[0]?workerFrom(result.rows[0]):undefined;}
  async listWorkers():Promise<WorkerRegistration[]>{const result=await this.database.query<any>('SELECT * FROM qualyntra_workers ORDER BY id');return result.rows.map(workerFrom);}
  async heartbeatWorker(id:string,now:string,state?:WorkerState):Promise<WorkerRegistration>{const result=state?await this.database.query<any>('UPDATE qualyntra_workers SET heartbeat_at=$2,state=$3 WHERE id=$1 RETURNING *',[id,now,state]):await this.database.query<any>('UPDATE qualyntra_workers SET heartbeat_at=$2 WHERE id=$1 RETURNING *',[id,now]);if(!result.rows[0])throw new Error(`Worker not registered: ${id}`);return workerFrom(result.rows[0]);}
  async leaseNext(workerId:string,options:LeaseOptions):Promise<DistributedExecutionJob|undefined>{return this.database.transaction(async tx=>{const workerResult=await tx.query<any>('SELECT * FROM qualyntra_workers WHERE id=$1 FOR UPDATE',[workerId]);if(!workerResult.rows[0])throw new Error(`Worker not registered: ${workerId}`);const worker=workerFrom(workerResult.rows[0]);if(worker.state!=='online'||Date.parse(options.now)-Date.parse(worker.heartbeatAt)>options.workerStaleMs||worker.activeLeases>=worker.maxConcurrency)return undefined;const s=storedScope(worker.scope);const candidates=await tx.query<any>("SELECT * FROM qualyntra_distributed_jobs WHERE state='queued' AND available_at<=$1 AND organization_id=$2 AND ($3='' OR workspace_id=$3) AND ($4='' OR project_id=$4) AND ($5='' OR environment_id=$5) AND (COALESCE(requirements_json->>'language','')='' OR requirements_json->>'language'=ANY($6::text[])) AND (COALESCE(requirements_json->>'runner','')='' OR requirements_json->>'runner'=ANY($7::text[])) AND (COALESCE(requirements_json->>'engine','')='' OR requirements_json->>'engine'=ANY($8::text[])) AND (COALESCE(requirements_json->>'operatingSystem','')='' OR requirements_json->>'operatingSystem'=ANY($9::text[])) AND (NOT (requirements_json ? 'labels') OR COALESCE(requirements_json->'labels','[]'::jsonb)<@$10::jsonb) ORDER BY created_at,id LIMIT $11 FOR UPDATE SKIP LOCKED",[options.now,s.organizationId,s.workspaceId,s.projectId,s.environmentId,worker.capabilities.languages,worker.capabilities.runners,worker.capabilities.engines??[],worker.capabilities.operatingSystems??[],JSON.stringify(worker.capabilities.labels??[]),this.candidateBatchSize]);const chosen=candidates.rows.map(jobFrom).find(job=>workerMatches(worker.capabilities,job.requirements));if(!chosen)return undefined;const leaseId=createId('lease');const expires=later(options.now,options.leaseMs);const updated=await tx.query<any>("UPDATE qualyntra_distributed_jobs SET state='leased',attempt=attempt+1,updated_at=$2,lease_id=$3,lease_worker_id=$4,lease_acquired_at=$2,lease_heartbeat_at=$2,lease_expires_at=$5 WHERE id=$1 RETURNING *",[chosen.id,options.now,leaseId,workerId,expires]);await tx.query('UPDATE qualyntra_workers SET active_leases=active_leases+1 WHERE id=$1',[workerId]);return jobFrom(updated.rows[0]);});}
  async heartbeatLease(jobId:string,leaseId:string,now:string,leaseMs:number):Promise<DistributedExecutionJob>{const expires=later(now,leaseMs);const result=await this.database.query<any>("UPDATE qualyntra_distributed_jobs SET lease_heartbeat_at=$3,lease_expires_at=$4,updated_at=$3 WHERE id=$1 AND lease_id=$2 AND state IN ('leased','running') AND lease_expires_at>=$3 RETURNING *",[jobId,leaseId,now,expires]);if(!result.rows[0])throw new Error(`Lease mismatch or expired for job: ${jobId}`);return jobFrom(result.rows[0]);}
  async markRunning(jobId:string,leaseId:string,now:string):Promise<DistributedExecutionJob>{const result=await this.database.query<any>("UPDATE qualyntra_distributed_jobs SET state='running',updated_at=$3 WHERE id=$1 AND lease_id=$2 AND state='leased' AND lease_expires_at>=$3 RETURNING *",[jobId,leaseId,now]);if(!result.rows[0])throw new Error(`Job is not actively leased: ${jobId}`);return jobFrom(result.rows[0]);}
  async complete(jobId:string,leaseId:string,result:ExecutionResult,now:string):Promise<DistributedExecutionJob>{return this.database.transaction(async tx=>{const job=await lockedJob(tx,jobId);assertActiveLease(job,leaseId,now);if(!['leased','running'].includes(job.state))throw new Error(`Job cannot complete from state ${job.state}`);await releaseWorker(tx,job.lease!.workerId);const state=result.status==='cancelled'?'cancelled':result.status==='passed'?'succeeded':'failed';const updated=await tx.query<any>('UPDATE qualyntra_distributed_jobs SET state=$2,updated_at=$3,result_json=$4::jsonb,lease_id=NULL,lease_worker_id=NULL,lease_acquired_at=NULL,lease_heartbeat_at=NULL,lease_expires_at=NULL WHERE id=$1 RETURNING *',[jobId,state,now,JSON.stringify(result)]);return jobFrom(updated.rows[0]);});}
  async fail(jobId:string,leaseId:string,input:{message:string;retryable:boolean;now:string;retryDelayMs?:number}):Promise<DistributedExecutionJob>{return this.database.transaction(async tx=>{const job=await lockedJob(tx,jobId);assertActiveLease(job,leaseId,input.now);await releaseWorker(tx,job.lease!.workerId);const retry=input.retryable&&job.attempt<job.maxAttempts;const state=retry?'queued':job.attempt>=job.maxAttempts?'dead-letter':'failed';const availableAt=retry?later(input.now,input.retryDelayMs??0):job.availableAt;const failure={message:input.message,retryable:input.retryable,failedAt:input.now};const updated=await tx.query<any>('UPDATE qualyntra_distributed_jobs SET state=$2,updated_at=$3,available_at=$4,failure_json=$5::jsonb,lease_id=NULL,lease_worker_id=NULL,lease_acquired_at=NULL,lease_heartbeat_at=NULL,lease_expires_at=NULL WHERE id=$1 RETURNING *',[jobId,state,input.now,availableAt,JSON.stringify(failure)]);return jobFrom(updated.rows[0]);});}
  async recoverExpired(now:string):Promise<{requeued:string[];deadLettered:string[];workersOffline:string[]}>{return this.database.transaction(async tx=>{const expired=await tx.query<any>("SELECT * FROM qualyntra_distributed_jobs WHERE state IN ('leased','running') AND lease_expires_at<$1 ORDER BY lease_expires_at,id FOR UPDATE SKIP LOCKED",[now]);const requeued:string[]=[];const deadLettered:string[]=[];const workersOffline=new Set<string>();for(const row of expired.rows){const job=jobFrom(row);const workerId=job.lease!.workerId;await releaseWorker(tx,workerId);await tx.query("UPDATE qualyntra_workers SET state='offline' WHERE id=$1",[workerId]);workersOffline.add(workerId);if(job.attempt<job.maxAttempts){await tx.query("UPDATE qualyntra_distributed_jobs SET state='queued',updated_at=$2,available_at=$2,lease_id=NULL,lease_worker_id=NULL,lease_acquired_at=NULL,lease_heartbeat_at=NULL,lease_expires_at=NULL WHERE id=$1",[job.id,now]);requeued.push(job.id);}else{const failure={message:'Execution lease expired.',retryable:true,failedAt:now};await tx.query("UPDATE qualyntra_distributed_jobs SET state='dead-letter',updated_at=$2,failure_json=$3::jsonb,lease_id=NULL,lease_worker_id=NULL,lease_acquired_at=NULL,lease_heartbeat_at=NULL,lease_expires_at=NULL WHERE id=$1",[job.id,now,JSON.stringify(failure)]);deadLettered.push(job.id);}}return{requeued,deadLettered,workersOffline:[...workersOffline]};});}
  async health(now:string,workerStaleMs:number):Promise<DistributedQueueHealth>{const cutoff=new Date(Date.parse(now)-workerStaleMs).toISOString();const counts=await this.database.query<any>("SELECT COUNT(*) FILTER (WHERE state='queued')::bigint AS queued,COUNT(*) FILTER (WHERE state='leased')::bigint AS leased,COUNT(*) FILTER (WHERE state='running')::bigint AS running FROM qualyntra_distributed_jobs");const workers=await this.database.query<any>("SELECT COUNT(*)::bigint AS total FROM qualyntra_workers WHERE state='online' AND heartbeat_at>=$1",[cutoff]);const row=counts.rows[0]??{};const queued=Number(row.queued??0),leased=Number(row.leased??0),running=Number(row.running??0),workersOnline=Number(workers.rows[0]?.total??0);return{status:queued>0&&workersOnline===0?'degraded':'healthy',queued,leased,running,workersOnline,checkedAt:now,message:queued>0&&workersOnline===0?'Queued work exists without an eligible online worker.':undefined};}
}
