/**
 * File: adapters/persistence/postgres/src/repository.ts
 * Purpose: Implements the tenant-safe Qualyntra control-plane repository on PostgreSQL with parameterized SQL and optimistic concurrency.
 * Author: Raushan Raj
 */
import type { ControlPlaneRepository,EvaluationRecord,PageRequest,PageResponse,RunRecord,StoredReleaseDecision } from '../../../../packages/contracts/src/control-plane';
import type { ReleasePolicy,TenantScope } from '../../../../packages/contracts/src/governance';
import type { ExecutionStatus } from '../../../../packages/contracts/src/execution';
import type { UniversalTestResult } from '../../../../packages/contracts/src/result';
import { OptimisticConcurrencyError } from '../../../../packages/persistence/src/errors';
import type { PostgresDatabase,PostgresQueryExecutor } from './driver';
import { exactScopeParams,restoredScope,scopeParams,storedScope } from './scope';

function json<T>(value:unknown):T{return(typeof value==='string'?JSON.parse(value):value) as T;}
function page<T>(rows:T[],request:PageRequest,total:number):PageResponse<T>{return{items:rows,offset:request.offset,limit:request.limit,total};}
function runFrom(row:any):RunRecord{return{id:String(row.id),scope:restoredScope(row),request:json(row.request_json),status:row.status,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),version:Number(row.version),idempotencyKey:row.idempotency_key??undefined,requestFingerprint:row.request_fingerprint??undefined};}
function evaluationFrom(row:any):EvaluationRecord{return{id:String(row.id),scope:restoredScope(row),profileId:String(row.profile_id),datasetId:String(row.dataset_id),status:row.status,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),metadata:row.metadata_json?json(row.metadata_json):undefined};}
async function count(executor:PostgresQueryExecutor,table:string,where:string,params:unknown[]):Promise<number>{const result=await executor.query<any>(`SELECT COUNT(*)::bigint AS total FROM ${table} WHERE ${where}`,params);return Number(result.rows[0]?.total??0);}
function policyKey(scope:TenantScope,id:string){const s=storedScope(scope);return[s.organizationId,s.workspaceId,s.projectId,s.environmentId,id];}

export class PostgresControlPlaneRepository implements ControlPlaneRepository{
  constructor(private readonly database:PostgresDatabase){}
  async createRun(record:RunRecord):Promise<RunRecord>{const s=storedScope(record.scope);await this.database.query('INSERT INTO qualyntra_runs (id,organization_id,workspace_id,project_id,environment_id,request_json,status,created_at,updated_at,version,idempotency_key,request_fingerprint) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12)',[record.id,s.organizationId,s.workspaceId,s.projectId,s.environmentId,JSON.stringify(record.request),record.status,record.createdAt,record.updatedAt,record.version,record.idempotencyKey??null,record.requestFingerprint??null]);return structuredClone(record);}
  async findRunByIdempotency(scope:TenantScope,key:string):Promise<RunRecord|undefined>{const s=exactScopeParams(scope);const result=await this.database.query<any>('SELECT * FROM qualyntra_runs WHERE organization_id=$1 AND workspace_id=$2 AND project_id=$3 AND environment_id=$4 AND idempotency_key=$5 LIMIT 1',[...s,key]);return result.rows[0]?runFrom(result.rows[0]):undefined;}
  async getRun(id:string,scope:TenantScope):Promise<RunRecord|undefined>{const scoped=scopeParams(scope,2);const result=await this.database.query<any>(`SELECT * FROM qualyntra_runs WHERE id=$1 AND ${scoped.sql} LIMIT 1`,[id,...scoped.params]);return result.rows[0]?runFrom(result.rows[0]):undefined;}
  async listRuns(scope:TenantScope,request:PageRequest):Promise<PageResponse<RunRecord>>{const scoped=scopeParams(scope);const total=await count(this.database,'qualyntra_runs',scoped.sql,scoped.params);const result=await this.database.query<any>(`SELECT * FROM qualyntra_runs WHERE ${scoped.sql} ORDER BY created_at,id LIMIT $5 OFFSET $6`,[...scoped.params,request.limit,request.offset]);return page(result.rows.map(runFrom),request,total);}
  async updateRunStatus(id:string,scope:TenantScope,expectedVersion:number,status:ExecutionStatus):Promise<RunRecord>{const scoped=scopeParams(scope,4);const now=new Date().toISOString();const result=await this.database.query<any>(`UPDATE qualyntra_runs SET status=$2,updated_at=$3,version=version+1 WHERE id=$1 AND ${scoped.sql} AND version=$8 RETURNING *`,[id,status,now,...scoped.params,expectedVersion]);if(result.rowCount===0)throw new OptimisticConcurrencyError('run',id,expectedVersion);return runFrom(result.rows[0]);}
  async saveResults(runId:string,scope:TenantScope,results:UniversalTestResult[]):Promise<void>{const run=await this.getRun(runId,scope);if(!run)throw new Error(`Run not found: ${runId}`);await this.database.transaction(async tx=>{await tx.query('DELETE FROM qualyntra_results WHERE run_id=$1',[runId]);for(let index=0;index<results.length;index++)await tx.query('INSERT INTO qualyntra_results (run_id,ordinal,result_id,result_json) VALUES ($1,$2,$3,$4::jsonb)',[runId,index,results[index]!.id,JSON.stringify(results[index])]);});}
  async listResults(runId:string,scope:TenantScope,request:PageRequest):Promise<PageResponse<UniversalTestResult>>{const run=await this.getRun(runId,scope);if(!run)throw new Error(`Run not found: ${runId}`);const totalResult=await this.database.query<any>('SELECT COUNT(*)::bigint AS total FROM qualyntra_results WHERE run_id=$1',[runId]);const result=await this.database.query<any>('SELECT result_json FROM qualyntra_results WHERE run_id=$1 ORDER BY ordinal LIMIT $2 OFFSET $3',[runId,request.limit,request.offset]);return page(result.rows.map(row=>json<UniversalTestResult>(row.result_json)),request,Number(totalResult.rows[0]?.total??0));}
  async createEvaluation(record:EvaluationRecord):Promise<EvaluationRecord>{const s=storedScope(record.scope);await this.database.query('INSERT INTO qualyntra_evaluations (id,organization_id,workspace_id,project_id,environment_id,profile_id,dataset_id,status,created_at,updated_at,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb)',[record.id,s.organizationId,s.workspaceId,s.projectId,s.environmentId,record.profileId,record.datasetId,record.status,record.createdAt,record.updatedAt,JSON.stringify(record.metadata??{})]);return structuredClone(record);}
  async getEvaluation(id:string,scope:TenantScope):Promise<EvaluationRecord|undefined>{const scoped=scopeParams(scope,2);const result=await this.database.query<any>(`SELECT * FROM qualyntra_evaluations WHERE id=$1 AND ${scoped.sql} LIMIT 1`,[id,...scoped.params]);return result.rows[0]?evaluationFrom(result.rows[0]):undefined;}
  async listEvaluations(scope:TenantScope,request:PageRequest):Promise<PageResponse<EvaluationRecord>>{const scoped=scopeParams(scope);const total=await count(this.database,'qualyntra_evaluations',scoped.sql,scoped.params);const result=await this.database.query<any>(`SELECT * FROM qualyntra_evaluations WHERE ${scoped.sql} ORDER BY created_at,id LIMIT $5 OFFSET $6`,[...scoped.params,request.limit,request.offset]);return page(result.rows.map(evaluationFrom),request,total);}
  async savePolicy(scope:TenantScope,policy:ReleasePolicy):Promise<void>{const [o,w,p,e,id]=policyKey(scope,policy.id);await this.database.query('INSERT INTO qualyntra_policies (organization_id,workspace_id,project_id,environment_id,policy_id,policy_json,updated_at) VALUES ($1,$2,$3,$4,$5,$6::jsonb,NOW()) ON CONFLICT (organization_id,workspace_id,project_id,environment_id,policy_id) DO UPDATE SET policy_json=EXCLUDED.policy_json,updated_at=NOW()',[o,w,p,e,id,JSON.stringify(policy)]);}
  async getPolicy(scope:TenantScope,id:string):Promise<ReleasePolicy|undefined>{const result=await this.database.query<any>('SELECT policy_json FROM qualyntra_policies WHERE organization_id=$1 AND workspace_id=$2 AND project_id=$3 AND environment_id=$4 AND policy_id=$5',policyKey(scope,id));return result.rows[0]?json(result.rows[0].policy_json):undefined;}
  async listPolicies(scope:TenantScope,request:PageRequest):Promise<PageResponse<ReleasePolicy>>{const scoped=scopeParams(scope);const total=await count(this.database,'qualyntra_policies',scoped.sql,scoped.params);const result=await this.database.query<any>(`SELECT policy_json FROM qualyntra_policies WHERE ${scoped.sql} ORDER BY policy_id LIMIT $5 OFFSET $6`,[...scoped.params,request.limit,request.offset]);return page(result.rows.map(row=>json<ReleasePolicy>(row.policy_json)),request,total);}
  async saveReleaseDecision(record:StoredReleaseDecision):Promise<void>{const s=storedScope(record.scope);await this.database.query('INSERT INTO qualyntra_release_decisions (id,release_id,organization_id,workspace_id,project_id,environment_id,decision_json,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8) ON CONFLICT (organization_id,workspace_id,project_id,environment_id,release_id) DO UPDATE SET id=EXCLUDED.id,decision_json=EXCLUDED.decision_json,created_at=EXCLUDED.created_at',[record.id,record.releaseId,s.organizationId,s.workspaceId,s.projectId,s.environmentId,JSON.stringify(record.decision),record.createdAt]);}
  async getReleaseDecision(releaseId:string,scope:TenantScope):Promise<StoredReleaseDecision|undefined>{const s=exactScopeParams(scope);const result=await this.database.query<any>('SELECT * FROM qualyntra_release_decisions WHERE organization_id=$1 AND workspace_id=$2 AND project_id=$3 AND environment_id=$4 AND release_id=$5 LIMIT 1',[...s,releaseId]);const row=result.rows[0];return row?{id:String(row.id),releaseId:String(row.release_id),scope:restoredScope(row),decision:json(row.decision_json),createdAt:new Date(row.created_at).toISOString()}:undefined;}
}
