/**
 * File: tests/ingestion/adapters.test.ts
 * Purpose: Verifies TRX, Allure, Cucumber, and Robot adapters normalize representative external results correctly.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { TrxResultAdapter } from '../../adapters/results/trx/src';import { AllureJsonResultAdapter } from '../../adapters/results/allure-json/src';import { CucumberJsonResultAdapter } from '../../adapters/results/cucumber-json/src';import { RobotXmlResultAdapter } from '../../adapters/results/robot-xml/src';
const runtime={language:'external',runner:'external'};
test('TRX adapter maps pass and failure outcomes',async()=>{const content='<TestRun><Results><UnitTestResult testName="ok" outcome="Passed" duration="00:00:01.250"/><UnitTestResult testName="bad" outcome="Failed"><Output><ErrorInfo><Message>boom</Message></ErrorInfo></Output></UnitTestResult></Results></TestRun>';const out=await new TrxResultAdapter().parse({content,runId:'r',runtime});assert.equal(out.length,2);assert.equal(out[0]?.durationMs,1250);assert.equal(out[1]?.status,'failed');assert.equal(out[1]?.failure?.message,'boom');});
test('Allure adapter maps labels attachments steps and status details',async()=>{const content=JSON.stringify({uuid:'u1',name:'login',status:'failed',start:1000,stop:1300,statusDetails:{message:'nope'},labels:[{name:'suite',value:'auth'},{name:'tag',value:'smoke'}],attachments:[{name:'shot',type:'image/png',source:'a.png'}],steps:[{name:'open',status:'passed',start:1000,stop:1100}]});const [out]=await new AllureJsonResultAdapter().parse({content,runId:'r',runtime});assert.equal(out?.suite,'auth');assert.equal(out?.status,'failed');assert.equal(out?.attachments?.[0]?.path,'a.png');assert.deepEqual(out?.tags,['smoke']);});
test('Cucumber adapter aggregates scenario step status and duration',async()=>{const content=JSON.stringify([{name:'Checkout',uri:'checkout.feature',elements:[{type:'scenario',name:'pay',tags:[{name:'@critical'}],steps:[{name:'given',result:{status:'passed',duration:2_000_000}},{name:'then',result:{status:'failed',duration:3_000_000,error_message:'expected'}}]}]}]);const [out]=await new CucumberJsonResultAdapter().parse({content,runId:'r',runtime});assert.equal(out?.status,'failed');assert.equal(out?.durationMs,5);assert.equal(out?.failure?.message,'expected');assert.deepEqual(out?.tags,['@critical']);});
test('Robot adapter maps PASS and FAIL test status blocks',async()=>{const content='<robot><suite name="S"><test id="s1-t1" name="ok"><status status="PASS" elapsed="0.25">All good</status></test><test id="s1-t2" name="bad"><status status="FAIL" elapsed="0.1">Assertion failed</status></test></suite></robot>';const out=await new RobotXmlResultAdapter().parse({content,runId:'r',runtime});assert.equal(out.length,2);assert.equal(out[0]?.status,'passed');assert.equal(out[0]?.durationMs,250);assert.equal(out[1]?.failure?.message,'Assertion failed');});
