/**
 * File: tests/ingestion/service.test.ts
 * Purpose: Verifies ingestion safety limits, metadata, deduplication, empty-result protection, and path confinement.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';import { promises as fs } from 'node:fs';import path from 'node:path';import { tmpdir } from 'node:os';
import { ResultIngestionService } from '../../packages/ingestion/src';import { createDefaultResultIngestionRegistry } from '../../adapters/results/default-registry/src';
const service=new ResultIngestionService(createDefaultResultIngestionRegistry());const runtime={language:'typescript',runner:'external'};
test('ingestion annotates source metadata and summary',async()=>{const content='<testsuite><testcase classname="a" name="one" time="0.1"/><testcase classname="a" name="two"><failure>bad</failure></testcase></testsuite>';const out=await service.ingest({runId:'run-1',runtime,path:'junit.xml',content,format:'junit-xml'});assert.equal(out.summary.total,2);assert.equal(out.summary.failed,1);assert.equal((out.results[0]?.metadata?.ingestion as any).format,'junit-xml');assert.equal(typeof (out.results[0]?.metadata?.ingestion as any).fingerprint,'string');});
test('ingestion optionally deduplicates exact normalized results',async()=>{const duplicate='<testsuite><testcase classname="a" name="same"/><testcase classname="a" name="same"/></testsuite>';const out=await service.ingest({runId:'r',runtime,content:duplicate,format:'junit-xml',deduplicate:true});assert.equal(out.results.length,1);assert.equal(out.summary.duplicateCount,1);});
test('ingestion rejects XML document type and entity declarations',async()=>{await assert.rejects(()=>service.ingest({runId:'r',runtime,content:'<!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]><testsuite/>',format:'junit-xml'}),/not allowed/);});
test('ingestion rejects result counts above configured maximum',async()=>{const content='<testsuite><testcase name="a"/><testcase name="b"/></testsuite>';await assert.rejects(()=>service.ingest({runId:'r',runtime,content,format:'junit-xml',limits:{maxResults:1}}),/exceeds configured limit/);});
test('ingestion fails closed when parser produces no tests by default',async()=>{await assert.rejects(()=>service.ingest({runId:'r',runtime,content:'<testsuite></testsuite>',format:'junit-xml'}),/produced no test results/);});
test('file ingestion confines real paths to configured root',async()=>{const root=await fs.mkdtemp(path.join(tmpdir(),'qualyntra-ingest-'));const inside=path.join(root,'results.xml');await fs.writeFile(inside,'<testsuite><testcase name="ok"/></testsuite>','utf8');const ok=await service.ingest({runId:'r',runtime,path:inside,allowedRoot:root,format:'junit-xml'});assert.equal(ok.results.length,1);const outside=path.join(tmpdir(),`qualyntra-outside-${Date.now()}.xml`);await fs.writeFile(outside,'<testsuite><testcase name="bad"/></testsuite>','utf8');await assert.rejects(()=>service.ingest({runId:'r',runtime,path:outside,allowedRoot:root,format:'junit-xml'}),/escapes the configured ingestion root/);await fs.rm(root,{recursive:true,force:true});await fs.rm(outside,{force:true});});
