/**
 * File: tests/integrations/enterprise-adapters.test.ts
 * Purpose: Verifies GitHub, Azure DevOps, Jira, and Jenkins adapters map vendor-neutral requests without live network access.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { GitHubIntegrationAdapter } from '../../adapters/integrations/github/src';
import { AzureDevOpsIntegrationAdapter } from '../../adapters/integrations/azure-devops/src';
import { JiraIntegrationAdapter } from '../../adapters/integrations/jira/src';
import { JenkinsIntegrationAdapter } from '../../adapters/integrations/jenkins/src';
import { SecretResolverRegistry } from '../../packages/security/src/secrets';
import type { IntegrationHttpRequest,IntegrationHttpResponse,IntegrationHttpTransport } from '../../packages/integrations/src';

class CaptureTransport implements IntegrationHttpTransport{requests:IntegrationHttpRequest[]=[];constructor(private readonly response:IntegrationHttpResponse={status:201,headers:{},body:{id:1,url:'result'}}){}async request(request:IntegrationHttpRequest){this.requests.push(request);return this.response;}}
function secrets(){const registry=new SecretResolverRegistry();registry.register({id:'test',supports:r=>r.provider==='test',async resolve(){return'token-value';}});return registry;}
const network={allowNetwork:true,allowedHosts:[]};const scope={organizationId:'org'};

test('GitHub publishes commit status with secret-resolved bearer auth and no embedded endpoint',async()=>{const transport=new CaptureTransport({status:201,headers:{'x-github-request-id':'g1','x-ratelimit-remaining':'49'},body:{id:11,html_url:'result'}});const adapter=new GitHubIntegrationAdapter({baseUrl:'https://git.example.test',owner:'acme',repository:'app',token:{provider:'test',key:'GH'},secrets:secrets(),networkPolicy:network,transport});const result=await adapter.execute({operation:'publish-status',scope,correlationId:'c1',payload:{sha:'abc',status:'PASS',description:'quality gate'}});assert.equal(result.ok,true);assert.equal(result.requestId,'g1');assert.equal(transport.requests[0]?.url,'https://git.example.test/repos/acme/app/statuses/abc');assert.equal(transport.requests[0]?.headers.authorization,'Bearer token-value');assert.equal(JSON.parse(transport.requests[0]?.body??'{}').state,'success');});

test('GitHub issue creation requires idempotency key and suppresses duplicates',async()=>{const transport=new CaptureTransport({status:201,headers:{},body:{id:22,html_url:'issue'}});const adapter=new GitHubIntegrationAdapter({baseUrl:'https://git.example.test',owner:'acme',repository:'app',token:{provider:'test',key:'GH'},secrets:secrets(),networkPolicy:network,transport});const request={operation:'create-work-item' as const,scope,correlationId:'c',idempotencyKey:'defect-1',payload:{title:'Failure'}};const first=await adapter.execute(request);const second=await adapter.execute(request);assert.equal(first.externalId,'22');assert.equal(second.externalId,'22');assert.equal(transport.requests.length,1);});

test('Azure DevOps maps commit status and work item creation to REST contracts',async()=>{const transport=new CaptureTransport({status:201,headers:{'x-vss-e2eid':'a1'},body:{id:30,url:'work'}});const adapter=new AzureDevOpsIntegrationAdapter({baseUrl:'https://ado.example.test',organization:'acme',project:'quality',credential:{provider:'test',key:'ADO'},authMode:'pat',secrets:secrets(),networkPolicy:network,transport});await adapter.execute({operation:'publish-status',scope,correlationId:'c',payload:{repositoryId:'repo',commitId:'abc',status:'PASS'}});assert.match(transport.requests[0]?.url??'',/_apis\/git\/repositories\/repo\/commits\/abc\/statuses\?api-version=7\.1$/);assert.match(transport.requests[0]?.headers.authorization??'',/^Basic /);await adapter.execute({operation:'create-work-item',scope,correlationId:'c2',idempotencyKey:'wi-1',payload:{type:'Bug',title:'Defect',description:'Details'}});assert.match(transport.requests[1]?.url??'',/_apis\/wit\/workitems\/\$Bug\?api-version=7\.1$/);assert.equal(transport.requests[1]?.headers['content-type'],'application/json-patch+json');});

test('Jira emits ADF issue/comment bodies and requires idempotency for issue creation',async()=>{const transport=new CaptureTransport({status:201,headers:{'atl-traceid':'j1'},body:{id:'101',key:'QA-1',self:'issue'}});const adapter=new JiraIntegrationAdapter({baseUrl:'https://jira.example.test',credential:{provider:'test',key:'JIRA'},authMode:'api-token',email:'qa@example.test',secrets:secrets(),networkPolicy:network,transport});await assert.rejects(()=>adapter.execute({operation:'create-work-item',scope,correlationId:'c',payload:{projectKey:'QA',issueType:'Bug',summary:'x'}}),/idempotencyKey/);const result=await adapter.execute({operation:'create-work-item',scope,correlationId:'c',idempotencyKey:'jira-1',payload:{projectKey:'QA',issueType:'Bug',summary:'Defect',description:'Observed'}});assert.equal(result.externalId,'QA-1');const body=JSON.parse(transport.requests[0]?.body??'{}');assert.equal(body.fields.description.type,'doc');assert.match(transport.requests[0]?.headers.authorization??'',/^Basic /);});

test('Jenkins triggers parameterized jobs using API token basic auth and encoded job path',async()=>{const transport=new CaptureTransport({status:201,headers:{location:'queue/item/1/'},body:undefined});const adapter=new JenkinsIntegrationAdapter({baseUrl:'https://jenkins.example.test',username:'ci-bot',apiToken:{provider:'test',key:'JENKINS'},secrets:secrets(),networkPolicy:network,transport});const result=await adapter.execute({operation:'trigger-build',scope,correlationId:'c',idempotencyKey:'build-1',payload:{jobPath:'folder/release',parameters:{ENV:'qa'}}});assert.equal(result.uri,'queue/item/1/');assert.equal(transport.requests[0]?.url,'https://jenkins.example.test/job/folder/job/release/buildWithParameters');assert.equal(transport.requests[0]?.body,'ENV=qa');assert.match(transport.requests[0]?.headers.authorization??'',/^Basic /);});

test('integration adapters fail closed when network policy blocks configured host',async()=>{const transport=new CaptureTransport();const adapter=new GitHubIntegrationAdapter({baseUrl:'https://git.example.test',owner:'a',repository:'b',token:{provider:'test',key:'GH'},secrets:secrets(),networkPolicy:{allowNetwork:false,allowedHosts:[]},transport});await assert.rejects(()=>adapter.execute({operation:'publish-status',scope,correlationId:'c',payload:{sha:'x',status:'PASS'}}),/Outbound network access is disabled/);assert.equal(transport.requests.length,0);});
