/**
 * File: apps/agent/src/main.ts
 * Purpose: Boots the standalone Qualyntra execution agent with secure credentials, adapter composition, capability discovery, health endpoints, and graceful drain.
 * Author: Raushan Raj
 */
import { AdapterRegistry } from '../../../packages/core/src/adapter-registry';
import { AgentControlPlaneClient,AgentEnvironmentSecretResolver,AgentFileSecretResolver,AgentWorkspaceManager,ExecutionAgentLifecycle,ExecutionAgentRuntime,FileAgentIdentityStore,createAgentTokenProvider,createExecutionAgentHealthServer,discoverAgentCapabilities,loadExecutionAgentConfiguration } from '../../../packages/agent/src';
import { registerBuiltInAgentRunners } from './builtins';

async function main(){const config=loadExecutionAgentConfiguration();if(config.runnerIds.length===0)throw new Error('QUALYNTRA_AGENT_RUNNERS must select at least one built-in runner.');const registry=new AdapterRegistry();registerBuiltInAgentRunners(registry,config.runnerIds);const discovered=await discoverAgentCapabilities(registry,{labels:config.labels,languages:config.languages,engines:config.engines});if(discovered.capabilities.runners.length===0)throw new Error('No configured execution-agent runner is currently available.');const workerId=await new FileAgentIdentityStore(config.dataDir).loadOrCreate();const client=new AgentControlPlaneClient({origin:config.controlPlaneOrigin,tokenProvider:createAgentTokenProvider(config),scope:config.scope});const resolvers:any[]=[new AgentFileSecretResolver(config.secretRoot)];if(config.allowEnvSecrets)resolvers.push(new AgentEnvironmentSecretResolver());const workspaces=new AgentWorkspaceManager(config.workspaceRoot,config.maxWorkspaceBytes,config.cleanupWorkspaces);const lifecycle=new ExecutionAgentLifecycle(workspaces,resolvers,client);const runtime=new ExecutionAgentRuntime(workerId,config.scope,discovered.capabilities,discovered.metadata,config.maxConcurrency,client,registry,lifecycle,{pollMs:config.pollMs,heartbeatMs:config.heartbeatMs,leaseMs:config.leaseMs,workerStaleMs:config.workerStaleMs,retryDelayMs:config.retryDelayMs,shutdownGraceMs:config.shutdownGraceMs});const health=createExecutionAgentHealthServer(runtime);await new Promise<void>((resolve,reject)=>{health.once('error',reject);health.listen(config.healthPort,config.healthHost,()=>resolve());});await runtime.start();console.log(`Qualyntra execution agent ${workerId} ready on ${config.healthHost}:${config.healthPort}`);let shuttingDown=false;const stop=async()=>{if(shuttingDown)return;shuttingDown=true;await runtime.stop();await new Promise<void>(resolve=>health.close(()=>resolve()));};for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{void stop().finally(()=>process.exit(0));});}
void main().catch(error=>{console.error(error instanceof Error?error.message:'Execution agent failed to start.');process.exit(1);});
