/**
 * File: adapters/llm/ollama/src/index.ts
 * Purpose: Implements Ollama chat generation for local or private endpoints using Qualyntra network policy and injectable transport.
 * Author: Raushan Raj
 */
import type { ModelProviderAdapter,ModelProviderCapabilities,ModelRequest,ModelResponse } from '../../../../packages/contracts/src/evaluation';
import type { NetworkPolicy } from '../../../../packages/contracts/src/configuration';
import { assertNetworkAllowed } from '../../../../packages/security/src/network-policy';
import { asRecord,FetchProviderHttpTransport,type ProviderHttpTransport } from '../../../../packages/providers/src/http';
import { capabilitiesWith,configuredHealth,endpoint,header,TEXT_CHAT_CAPABILITIES } from '../../../../packages/providers/src/adapter-utils';
export interface OllamaOptions{id?:string;baseUrl:string;model:string;networkPolicy:NetworkPolicy;bearerToken?:string;headers?:Record<string,string>;timeoutMs?:number;transport?:ProviderHttpTransport;capabilities?:Partial<ModelProviderCapabilities>;}
export class OllamaProvider implements ModelProviderAdapter{readonly id:string;private readonly transport:ProviderHttpTransport;constructor(private readonly options:OllamaOptions){this.id=options.id??'ollama';this.transport=options.transport??new FetchProviderHttpTransport();}capabilities(){return capabilitiesWith(TEXT_CHAT_CAPABILITIES,this.options.capabilities);}health(){return Promise.resolve(configuredHealth(this.options.baseUrl,this.options.networkPolicy,true));}async generate(request:ModelRequest):Promise<ModelResponse>{assertNetworkAllowed(this.options.baseUrl,this.options.networkPolicy);const started=Date.now();const headers:Record<string,string>={'content-type':'application/json',...this.options.headers};if(this.options.bearerToken)headers.authorization=`Bearer ${this.options.bearerToken}`;const response=await this.transport.request({providerId:this.id,url:endpoint(this.options.baseUrl,'/api/chat'),method:'POST',headers,timeoutMs:request.timeoutMs??this.options.timeoutMs,body:JSON.stringify({model:request.model??this.options.model,messages:request.messages.map(m=>({role:m.role,content:m.content})),stream:false,options:{...(request.temperature===undefined?{}:{temperature:request.temperature}),...(request.maxTokens===undefined?{}:{num_predict:request.maxTokens})}})});const body=asRecord(response.body);const inputTokens=num(body.prompt_eval_count);const outputTokens=num(body.eval_count);return{content:String(asRecord(body.message).content??''),model:String(body.model??request.model??this.options.model),provider:this.id,latencyMs:Date.now()-started,inputTokens,outputTokens,totalTokens:(inputTokens??0)+(outputTokens??0),requestId:header(response.headers,'x-request-id','request-id'),raw:body};}}
function num(value:unknown):number|undefined{return typeof value==='number'&&Number.isFinite(value)?value:undefined;}
