/**
 * File: tests/control-plane/api.test.ts
 * Purpose: Exercises the versioned control-plane API over real local HTTP for authentication, RBAC, tenancy, idempotency, governance, audit, CORS, and safe errors.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { AdapterRegistry } from '../../packages/core/src/adapter-registry';
import { InMemoryAuditLog,RbacAuthorizer,GovernanceService } from '../../packages/governance/src';
import { IntegrationService } from '../../packages/integrations/src';
import { ControlPlaneService,FixedWindowRateLimiter,InMemoryControlPlaneRepository,StaticBearerAuthenticator,createBuiltInRoleCatalog,createControlPlaneServer } from '../../packages/control-plane/src';

async function harness(options:{maxBodyBytes?:number;rateLimit?:number;corsOrigins?:string[]}={}){
  const actor={id:'admin',type:'service' as const,assignments:[{roleId:'platform-admin',scope:{organizationId:'o1'}}]};
  const auth=new StaticBearerAuthenticator('test-token',actor);const roles=createBuiltInRoleCatalog();const audit=new InMemoryAuditLog();const governance=new GovernanceService(new RbacAuthorizer(roles),audit);const registry=new AdapterRegistry();
  registry.register({descriptor:{id:'runtime-demo',kind:'runtime',version:'1',displayName:'Runtime Demo',description:'test',capabilities:['health']},async health(){return{status:'healthy' as const,checkedAt:new Date().toISOString()};}});
  registry.register({descriptor:{id:'integration-demo',kind:'integration',version:'1',displayName:'Integration Demo',description:'test',capabilities:['publish-status']},async health(){return{status:'healthy' as const,checkedAt:new Date().toISOString()};},async execute(){return{ok:true,externalId:'ext-1'};}} as any);
  const repository=new InMemoryControlPlaneRepository();const service=new ControlPlaneService(repository,governance,registry,new IntegrationService(registry),audit);
  const server=createControlPlaneServer({authenticator:auth,governance,service,rateLimiter:new FixedWindowRateLimiter(options.rateLimit??100),options:{maxBodyBytes:options.maxBodyBytes??4096,maxPageSize:25,corsOrigins:options.corsOrigins??[]},readiness:async()=>({ready:true,checks:{repository:'ready'}})});
  await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});
  const address=server.address();const port=typeof address==='object'&&address?address.port:0;return{base:`http://127.0.0.1:${port}`,server,audit};
}
function headers(extra:Record<string,string>={}):Record<string,string>{return{authorization:'Bearer test-token','content-type':'application/json','x-qualyntra-organization-id':'o1','x-qualyntra-workspace-id':'w1','x-qualyntra-project-id':'p1',...extra};}
async function body(response:any):Promise<any>{return response.json();}

test('health is public while protected capabilities require authentication',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());assert.equal((await fetch(`${h.base}/api/v1/health`)).status,200);const denied=await fetch(`${h.base}/api/v1/capabilities`,{headers:{'x-qualyntra-organization-id':'o1'}});assert.equal(denied.status,401);assert.equal((await body(denied)).error.code,'unauthorized');});
test('protected routes require explicit tenant context',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const response=await fetch(`${h.base}/api/v1/capabilities`,{headers:{authorization:'Bearer test-token'}});assert.equal(response.status,400);assert.equal((await body(response)).error.code,'tenant_context_required');});
test('rbac denies an authenticated actor crossing organization boundaries',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const response=await fetch(`${h.base}/api/v1/capabilities`,{headers:headers({'x-qualyntra-organization-id':'o2'})});assert.equal(response.status,403);});
test('control plane generates run ids and rejects persisted raw environment values',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const generated=await body(await fetch(`${h.base}/api/v1/runs`,{method:'POST',headers:headers(),body:JSON.stringify({runId:'client-controlled',projectId:'p1',runtime:{language:'typescript',runner:'playwright-test'}})}));assert.notEqual(generated.id,'client-controlled');const rejected=await fetch(`${h.base}/api/v1/runs`,{method:'POST',headers:headers(),body:JSON.stringify({projectId:'p1',runtime:{language:'typescript',runner:'playwright-test'},env:{API_TOKEN:'secret'}})});assert.equal(rejected.status,400);assert.equal((await body(rejected)).error.code,'raw_environment_not_allowed');});
test('run creation is idempotent and rejects key reuse with a different request',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const endpoint=`${h.base}/api/v1/runs`;const firstPayload={projectId:'p1',runtime:{language:'typescript',runner:'playwright-test'}};const first=await fetch(endpoint,{method:'POST',headers:headers({'idempotency-key':'idem-1'}),body:JSON.stringify(firstPayload)});assert.equal(first.status,201);const firstBody=await body(first);const second=await fetch(endpoint,{method:'POST',headers:headers({'idempotency-key':'idem-1'}),body:JSON.stringify(firstPayload)});assert.equal(second.status,200);assert.equal((await body(second)).id,firstBody.id);const conflict=await fetch(endpoint,{method:'POST',headers:headers({'idempotency-key':'idem-1'}),body:JSON.stringify({...firstPayload,runtime:{language:'python',runner:'pytest'}})});assert.equal(conflict.status,409);});
test('runs and normalized results round-trip through tenant-scoped repositories',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const created=await body(await fetch(`${h.base}/api/v1/runs`,{method:'POST',headers:headers(),body:JSON.stringify({projectId:'p1',runtime:{language:'python',runner:'pytest'}})}));const result={id:'t1',runId:'wrong',name:'sample',status:'passed',durationMs:1,runtime:{language:'python',runner:'pytest'}};const save=await fetch(`${h.base}/api/v1/runs/${created.id}/results`,{method:'POST',headers:headers(),body:JSON.stringify([result])});assert.equal(save.status,202);const listed=await body(await fetch(`${h.base}/api/v1/runs/${created.id}/results?limit=10`,{headers:headers()}));assert.equal(listed.items[0].runId,created.id);});
test('invalid normalized results fail with a safe contract error',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const created=await body(await fetch(`${h.base}/api/v1/runs`,{method:'POST',headers:headers(),body:JSON.stringify({projectId:'p1',runtime:{language:'python',runner:'pytest'}})}));const response=await fetch(`${h.base}/api/v1/runs/${created.id}/results`,{method:'POST',headers:headers(),body:JSON.stringify([{name:'missing fields'}])});assert.equal(response.status,400);assert.equal((await body(response)).error.code,'invalid_results');});
test('policy creation and release evaluation return evidence-backed decisions',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const policy={id:'prod',name:'Production',rules:[{id:'critical',description:'No critical failures',fact:'criticalFailures',operator:'eq',expected:0,severity:'block'}]};assert.equal((await fetch(`${h.base}/api/v1/policies`,{method:'POST',headers:headers(),body:JSON.stringify(policy)})).status,201);const response=await fetch(`${h.base}/api/v1/releases/r1/decision`,{method:'POST',headers:headers(),body:JSON.stringify({policyId:'prod',facts:[{key:'criticalFailures',value:0}]})});assert.equal(response.status,200);assert.equal((await body(response)).decision.status,'PASS');});
test('audit endpoint exposes only records inside the requested tenant hierarchy',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());await fetch(`${h.base}/api/v1/capabilities`,{headers:headers()});const response=await fetch(`${h.base}/api/v1/audit`,{headers:headers()});const data=await body(response);assert.equal(response.status,200);assert.ok(data.total>=2);assert.ok(data.items.every((item:any)=>!item.scope||item.scope.organizationId==='o1'));});
test('adapter discovery and integration execution stay behind adapter contracts',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const runtimes=await body(await fetch(`${h.base}/api/v1/runtimes`,{headers:headers()}));assert.equal(runtimes.items[0].id,'runtime-demo');const executed=await fetch(`${h.base}/api/v1/integrations/integration-demo/actions`,{method:'POST',headers:headers(),body:JSON.stringify({operation:'publish-status',payload:{status:'PASS'}})});assert.equal(executed.status,200);assert.equal((await body(executed)).externalId,'ext-1');});
test('payload limits fail before oversized JSON reaches business logic',async (t:any)=>{const h=await harness({maxBodyBytes:128});t.after(()=>h.server.close());const response=await fetch(`${h.base}/api/v1/runs`,{method:'POST',headers:headers(),body:JSON.stringify({projectId:'p1',runtime:{language:'typescript',runner:'playwright-test'},metadata:{large:'x'.repeat(500)}})});assert.equal(response.status,413);assert.equal((await body(response)).error.code,'payload_too_large');});
test('rate limiting returns 429 and retry-after without internal errors',async (t:any)=>{const h=await harness({rateLimit:1});t.after(()=>h.server.close());assert.equal((await fetch(`${h.base}/api/v1/capabilities`,{headers:headers()})).status,200);const response=await fetch(`${h.base}/api/v1/capabilities`,{headers:headers()});assert.equal(response.status,429);assert.ok(response.headers.get('retry-after'));});
test('configured CORS reflects only allowlisted origins and handles preflight',async (t:any)=>{const h=await harness({corsOrigins:['https://allowed.example']});t.after(()=>h.server.close());const allowed=await fetch(`${h.base}/api/v1/health`,{headers:{origin:'https://allowed.example'}});assert.equal(allowed.headers.get('access-control-allow-origin'),'https://allowed.example');const denied=await fetch(`${h.base}/api/v1/health`,{headers:{origin:'https://blocked.example'}});assert.equal(denied.headers.get('access-control-allow-origin'),null);const preflight=await fetch(`${h.base}/api/v1/runs`,{method:'OPTIONS',headers:{origin:'https://allowed.example'}});assert.equal(preflight.status,204);});
test('invalid JSON and unknown routes use stable error envelopes without stack traces',async (t:any)=>{const h=await harness();t.after(()=>h.server.close());const invalid=await fetch(`${h.base}/api/v1/runs`,{method:'POST',headers:headers(),body:'{' });const invalidBody=await body(invalid);assert.equal(invalid.status,400);assert.equal(invalidBody.error.code,'invalid_json');assert.equal('stack' in invalidBody.error,false);const missing=await fetch(`${h.base}/api/v1/not-here`,{headers:headers()});assert.equal(missing.status,404);});
