/**
 * File: tests/control-plane/observability-notifications.test.ts
 * Purpose: Verifies observability summaries, alert listing, notification discovery, and RBAC-protected delivery over the real control-plane HTTP boundary.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { AdapterRegistry } from '../../packages/core/src/adapter-registry';
import { InMemoryAuditLog,RbacAuthorizer,GovernanceService } from '../../packages/governance/src';
import { IntegrationService } from '../../packages/integrations/src';
import { NotificationService } from '../../packages/notifications/src';
import { AlertEngine,InMemoryAlertStateStore,InMemoryTelemetryStore,ObservabilityService } from '../../packages/observability/src';
import { ControlPlaneService,FixedWindowRateLimiter,InMemoryControlPlaneRepository,StaticBearerAuthenticator,createBuiltInRoleCatalog,createControlPlaneServer } from '../../packages/control-plane/src';

test('control plane exposes tenant-aware observability and notification APIs',async(t:any)=>{const actor={id:'admin',type:'service' as const,assignments:[{roleId:'platform-admin',scope:{organizationId:'o1'}}]};const audit=new InMemoryAuditLog();const governance=new GovernanceService(new RbacAuthorizer(createBuiltInRoleCatalog()),audit);const registry=new AdapterRegistry();let delivered=0;registry.register({descriptor:{id:'notify-demo',kind:'notification',version:'1',displayName:'Notify Demo',description:'test',capabilities:['notify']},async health(){return{status:'healthy' as const,checkedAt:new Date().toISOString()};},async execute(){delivered++;return{ok:true,externalId:'sent-1'};}} as any);const notifications=new NotificationService(registry,audit);const telemetry=new InMemoryTelemetryStore();const alertState=new InMemoryAlertStateStore();const observability=new ObservabilityService(telemetry,telemetry,new AlertEngine([],alertState,notifications),alertState);await observability.recordMetric({id:'m1',timestamp:new Date().toISOString(),name:'runs.failed',kind:'gauge',value:2,resource:{serviceName:'control-plane'},scope:{organizationId:'o1'}});const service=new ControlPlaneService(new InMemoryControlPlaneRepository(),governance,registry,new IntegrationService(registry),audit,observability,notifications);const server=createControlPlaneServer({authenticator:new StaticBearerAuthenticator('token',actor),governance,service,rateLimiter:new FixedWindowRateLimiter(100),options:{maxBodyBytes:4096,maxPageSize:25,corsOrigins:[]}});await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});t.after(()=>server.close());const address=server.address();const base=`http://127.0.0.1:${typeof address==='object'&&address?address.port:0}`;const headers={authorization:'Bearer token','content-type':'application/json','x-qualyntra-organization-id':'o1'};const summary=await (await fetch(`${base}/api/v1/observability/summary`,{headers})).json() as any;assert.equal(summary.counts.metrics,1);const descriptors=await (await fetch(`${base}/api/v1/notifications`,{headers})).json() as any;assert.equal(descriptors.items[0].id,'notify-demo');const sent=await fetch(`${base}/api/v1/notifications/notify-demo/actions`,{method:'POST',headers:{...headers,'idempotency-key':'notice-1'},body:JSON.stringify({title:'Release blocked',message:'Quality gate failed',severity:'critical'})});assert.equal(sent.status,200);assert.equal((await sent.json() as any).externalId,'sent-1');assert.equal(delivered,1);const alerts=await (await fetch(`${base}/api/v1/alerts`,{headers})).json() as any;assert.equal(alerts.total,0);});
