/**
 * File: tests/artifacts/remote-storage.test.ts
 * Purpose: Verifies S3-compatible and Azure Blob artifact adapter boundaries, network policy, grant safety, and SDK-neutral client delegation.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { S3ArtifactStorageAdapter,type S3ArtifactClient } from '../../adapters/storage/s3/src/index';
import { AzureBlobArtifactStorageAdapter,type AzureBlobArtifactClient } from '../../adapters/storage/azure-blob/src/index';
async function* bytes(value:string){yield new TextEncoder().encode(value);}async function collect(body:AsyncIterable<Uint8Array>){let n=0;for await(const chunk of body)n+=chunk.byteLength;return n;}
const policy={allowNetwork:true,allowedHosts:['storage.example.test']};

test('S3-compatible adapter delegates object operations and time-limited presigning without SDK coupling',async()=>{let key='';const client:S3ArtifactClient={async putObject(input){key=input.key;return{sizeBytes:await collect(input.body),etag:'e'};},async getObject(){return bytes('x');},async headObject(){return{contentType:'text/plain',sizeBytes:1};},async deleteObject(){},async presignGetObject(input){return{url:`https://storage.example.test/${input.key}?signed=1`,expiresAt:new Date(Date.now()+input.expiresInSeconds*1000).toISOString()};}};const adapter=new S3ArtifactStorageAdapter({endpoint:'https://storage.example.test',bucket:'artifacts',networkPolicy:policy},client);const result=await adapter.put({key:'k',contentType:'text/plain',body:bytes('abc')});assert.equal(result.sizeBytes,3);assert.equal(key,'k');assert.match((await adapter.createDownloadGrant({key:'k',expiresInSeconds:60})).url,/signed=1/);});

test('Azure Blob adapter delegates to container/blob primitives and accepts secure user-delegation style grants',async()=>{let blob='';const client:AzureBlobArtifactClient={async putBlob(input){blob=input.blobName;return{sizeBytes:await collect(input.body)};},async getBlob(){return bytes('x');},async headBlob(){return{contentType:'text/plain',sizeBytes:1};},async deleteBlob(){},async createReadGrant(input){return{url:`https://storage.example.test/c/${input.blobName}?sas=1`,expiresAt:new Date(Date.now()+input.expiresInSeconds*1000).toISOString()};}};const adapter=new AzureBlobArtifactStorageAdapter({endpoint:'https://storage.example.test',container:'c',networkPolicy:policy},client);await adapter.put({key:'k',contentType:'text/plain',body:bytes('abc')});assert.equal(blob,'k');assert.match((await adapter.createDownloadGrant({key:'k',expiresInSeconds:30})).url,/sas=1/);});

test('remote artifact adapters enforce outbound network policy before client invocation',async()=>{let called=false;const client:S3ArtifactClient={async putObject(){called=true;return{sizeBytes:0};},async getObject(){called=true;return bytes('');},async headObject(){called=true;return undefined;},async deleteObject(){called=true;},async presignGetObject(){called=true;throw new Error('should not run');}};const adapter=new S3ArtifactStorageAdapter({endpoint:'https://storage.example.test',bucket:'b',networkPolicy:{allowNetwork:false,allowedHosts:[]}},client);await assert.rejects(()=>adapter.delete('k'),/network access is disabled/i);assert.equal(called,false);});

test('remote artifact adapters reject insecure non-local download grants',async()=>{const client:S3ArtifactClient={async putObject(){return{sizeBytes:0};},async getObject(){return bytes('');},async headObject(){return undefined;},async deleteObject(){},async presignGetObject(input){return{url:'http://storage.example.test/object',expiresAt:new Date(Date.now()+input.expiresInSeconds*1000).toISOString()};}};const adapter=new S3ArtifactStorageAdapter({endpoint:'https://storage.example.test',bucket:'b',networkPolicy:policy},client);await assert.rejects(()=>adapter.createDownloadGrant({key:'k',expiresInSeconds:60}),/must use HTTPS/);});
