/**
 * File: adapters/llm/gemini/src/index.ts
 * Purpose: Implements Gemini generateContent text generation with API-key headers, network policy, and injectable transport.
 * Author: Raushan Raj
 */
import type { ModelProviderAdapter,ModelProviderCapabilities,ModelRequest,ModelResponse } from '../../../../packages/contracts/src/evaluation';
import type { NetworkPolicy } from '../../../../packages/contracts/src/configuration';
import { assertNetworkAllowed } from '../../../../packages/security/src/network-policy';
import { asRecord,FetchProviderHttpTransport,type ProviderHttpTransport } from '../../../../packages/providers/src/http';
import { capabilitiesWith,configuredHealth,endpoint,header,TEXT_CHAT_CAPABILITIES } from '../../../../packages/providers/src/adapter-utils';
export interface GeminiOptions{id?:string;baseUrl:string;apiKey:string;model:string;networkPolicy:NetworkPolicy;headers?:Record<string,string>;timeoutMs?:number;transport?:ProviderHttpTransport;capabilities?:Partial<ModelProviderCapabilities>;}
export class GeminiProvider implements ModelProviderAdapter{readonly id:string;private readonly transport:ProviderHttpTransport;constructor(private readonly options:GeminiOptions){this.id=options.id??'gemini';this.transport=options.transport??new FetchProviderHttpTransport();}capabilities(){return capabilitiesWith(TEXT_CHAT_CAPABILITIES,this.options.capabilities);}health(){return Promise.resolve(configuredHealth(this.options.baseUrl,this.options.networkPolicy,Boolean(this.options.apiKey)));}async generate(request:ModelRequest):Promise<ModelResponse>{assertNetworkAllowed(this.options.baseUrl,this.options.networkPolicy);const started=Date.now();const model=request.model??this.options.model;const system=request.messages.filter(m=>m.role==='system').map(m=>m.content).join('\n');const contents=request.messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const response=await this.transport.request({providerId:this.id,url:endpoint(this.options.baseUrl,`/v1beta/models/${encodeURIComponent(model)}:generateContent`),method:'POST',timeoutMs:request.timeoutMs??this.options.timeoutMs,headers:{'content-type':'application/json','x-goog-api-key':this.options.apiKey,...this.options.headers},body:JSON.stringify({contents,...(system?{systemInstruction:{parts:[{text:system}]}}:{}),generationConfig:{...(request.temperature===undefined?{}:{temperature:request.temperature}),...(request.maxTokens===undefined?{}:{maxOutputTokens:request.maxTokens})}})});const body=asRecord(response.body);const usage=asRecord(body.usageMetadata);const candidate=Array.isArray(body.candidates)?asRecord(body.candidates[0]):{};const content=asRecord(candidate.content);const text=(Array.isArray(content.parts)?content.parts:[]).map(part=>asRecord(part).text).filter((v):v is string=>typeof v==='string').join('');const inputTokens=num(usage.promptTokenCount);const outputTokens=num(usage.candidatesTokenCount);return{content:text,model,provider:this.id,latencyMs:Date.now()-started,inputTokens,outputTokens,totalTokens:num(usage.totalTokenCount)??((inputTokens??0)+(outputTokens??0)),requestId:header(response.headers,'x-request-id','request-id'),raw:body};}}
function num(value:unknown):number|undefined{return typeof value==='number'&&Number.isFinite(value)?value:undefined;}
