/**
 * File: adapters/integrations/jira/src/index.ts
 * Purpose: Implements Jira issue creation and comments with ADF payloads, idempotency protection, and secret-reference authentication.
 * Author: Raushan Raj
 */
import type { AdapterHealth,IntegrationAdapter,IntegrationRequest,IntegrationResponse,NetworkPolicy,SecretReference } from '../../../../packages/contracts/src';
import type { SecretResolverRegistry } from '../../../../packages/security/src/secrets';
import { assertNetworkAllowed } from '../../../../packages/security/src/network-policy';
import { asIntegrationRecord,FetchIntegrationHttpTransport,type IntegrationHttpTransport } from '../../../../packages/integrations/src/http';
import { dedupe,InMemoryIntegrationDedupeStore,type IntegrationDedupeStore } from '../../../../packages/integrations/src/dedupe';
import { withIntegrationRetry,type IntegrationRetryPolicy } from '../../../../packages/integrations/src/retry';
import { basicHeader,bearerHeader,encodeSegment,endpoint,optionalString,rateLimit,requiredString } from '../../../../packages/integrations/src/utils';

export interface JiraIntegrationOptions{id?:string;baseUrl:string;credential:SecretReference;authMode:'bearer'|'api-token';email?:string;secrets:SecretResolverRegistry;networkPolicy:NetworkPolicy;transport?:IntegrationHttpTransport;timeoutMs?:number;headers?:Record<string,string>;retryPolicy?:IntegrationRetryPolicy;dedupeStore?:IntegrationDedupeStore;}
export class JiraIntegrationAdapter implements IntegrationAdapter{
  readonly descriptor;private readonly transport;private readonly dedupeStore;
  constructor(private readonly options:JiraIntegrationOptions){if(options.authMode==='api-token'&&!options.email)throw new Error('Jira api-token authentication requires email');this.descriptor={id:options.id??'jira',kind:'integration' as const,version:'1.0.0',displayName:'Jira',description:'Jira issue and comment integration',capabilities:['create-work-item','comment'],supportedTools:['jira']};this.transport=options.transport??new FetchIntegrationHttpTransport();this.dedupeStore=options.dedupeStore??new InMemoryIntegrationDedupeStore();}
  async health():Promise<AdapterHealth>{try{const url=endpoint(this.options.baseUrl,'rest/api/3');assertNetworkAllowed(url,this.options.networkPolicy);return{status:'healthy',message:'configured; no remote health request performed',checkedAt:new Date().toISOString()};}catch(error){return{status:'unavailable',message:error instanceof Error?error.message:'invalid configuration',checkedAt:new Date().toISOString()};}}
  async execute(request:IntegrationRequest):Promise<IntegrationResponse>{switch(request.operation){case'create-work-item':return this.createIssue(request);case'comment':return this.comment(request);default:throw new Error(`Jira integration does not support operation: ${request.operation}`);}}
  private async createIssue(request:IntegrationRequest){if(!request.idempotencyKey)throw new Error('Jira create-work-item requires idempotencyKey to prevent duplicate defects');const projectKey=requiredString(request.payload,'projectKey');const issueType=requiredString(request.payload,'issueType');const summary=requiredString(request.payload,'summary');const description=optionalString(request.payload,'description');const extra=request.payload.fields&&typeof request.payload.fields==='object'?request.payload.fields as Record<string,unknown>:{};const fields:any={...extra,project:{key:projectKey},issuetype:{name:issueType},summary};if(description)fields.description=adf(description);return this.post(request,'rest/api/3/issue',{fields},request.idempotencyKey);}
  private async comment(request:IntegrationRequest){const issueKey=requiredString(request.payload,'issueKey');const body=requiredString(request.payload,'body');return this.post(request,`rest/api/3/issue/${encodeSegment(issueKey)}/comment`,{body:adf(body)},request.idempotencyKey);}
  private async auth(){return this.options.authMode==='bearer'?bearerHeader(this.options.secrets,this.options.credential):basicHeader(this.options.secrets,this.options.credential,this.options.email??'');}
  private async post(request:IntegrationRequest,path:string,body:unknown,dedupeKey?:string):Promise<IntegrationResponse>{const key=dedupeKey?`${this.descriptor.id}:${request.scope.organizationId}:${request.operation}:${dedupeKey}`:undefined;return dedupe(this.dedupeStore,key,async()=>withIntegrationRetry(async()=>{const url=endpoint(this.options.baseUrl,path);assertNetworkAllowed(url,this.options.networkPolicy);const response=await this.transport.request({adapterId:this.descriptor.id,url,method:'POST',headers:{accept:'application/json','content-type':'application/json',authorization:await this.auth(),...this.options.headers},body:JSON.stringify(body),timeoutMs:this.options.timeoutMs});const value=asIntegrationRecord(response.body);return{ok:true,externalId:value.key??(value.id===undefined?undefined:String(value.id)),uri:typeof value.self==='string'?value.self:undefined,requestId:response.headers['x-request-id']??response.headers['atl-traceid'],rateLimit:rateLimit(response.headers),metadata:{status:response.status}};},{idempotent:Boolean(dedupeKey),policy:this.options.retryPolicy}));}
}
function adf(text:string){return{version:1,type:'doc',content:[{type:'paragraph',content:[{type:'text',text}]}]};}
