/**
 * File: tests/persistence/postgres-sql.test.ts
 * Purpose: Verifies PostgreSQL repository queries remain parameterized, tenant-scoped, and optimistic-concurrency aware without requiring a live database.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { PostgresControlPlaneRepository } from '../../adapters/persistence/postgres/src/repository';
import { OptimisticConcurrencyError } from '../../packages/persistence/src/errors';
class ScriptedDb{calls:{text:string;params:unknown[]}[]=[];responses:any[]=[];async query<T>(text:string,params:unknown[]=[]){this.calls.push({text,params});return(this.responses.shift()??{rows:[],rowCount:0}) as T as any;}async transaction<T>(work:any){return work({id:'tx',query:this.query.bind(this)});} }
function row(){return{id:'r1',organization_id:'o1',workspace_id:'w1',project_id:'p1',environment_id:'',request_json:{runId:'r1',projectId:'p1',runtime:{language:'typescript',runner:'playwright-test'}},status:'running',created_at:'2026-09-17T00:00:00.000Z',updated_at:'2026-09-17T00:00:01.000Z',version:2,idempotency_key:'idem',request_fingerprint:'fp'};}
test('create run uses placeholders instead of interpolating tenant/request data',async()=>{const db=new ScriptedDb();const repo=new PostgresControlPlaneRepository(db as any);await repo.createRun({id:'r1',scope:{organizationId:'o1',workspaceId:'w1',projectId:'p1'},request:{runId:'r1',projectId:'p1',runtime:{language:'typescript',runner:'playwright-test'}},status:'queued',createdAt:'2026-09-17T00:00:00.000Z',updatedAt:'2026-09-17T00:00:00.000Z',version:1,idempotencyKey:'idem',requestFingerprint:'fp'});assert.match(db.calls[0]!.text,/VALUES \(\$1,\$2/);assert.equal(db.calls[0]!.text.includes('o1'),false);assert.equal(db.calls[0]!.params[1],'o1');});
test('hierarchical list query scopes every tenant level and paginates with parameters',async()=>{const db=new ScriptedDb();db.responses.push({rows:[{total:'1'}],rowCount:1},{rows:[row()],rowCount:1});const repo=new PostgresControlPlaneRepository(db as any);const result=await repo.listRuns({organizationId:'o1',workspaceId:'w1',projectId:'p1'},{offset:5,limit:10});assert.equal(result.total,1);assert.match(db.calls[1]!.text,/organization_id=\$1/);assert.deepEqual(db.calls[1]!.params,['o1','w1','p1','',10,5]);});
test('optimistic status update increments version and rejects stale writers',async()=>{const db=new ScriptedDb();db.responses.push({rows:[row()],rowCount:1});const repo=new PostgresControlPlaneRepository(db as any);const updated=await repo.updateRunStatus('r1',{organizationId:'o1',workspaceId:'w1',projectId:'p1'},1,'running');assert.equal(updated.version,2);assert.match(db.calls[0]!.text,/version=version\+1/);const staleDb=new ScriptedDb();const stale=new PostgresControlPlaneRepository(staleDb as any);await assert.rejects(()=>stale.updateRunStatus('r1',{organizationId:'o1'},1,'running'),OptimisticConcurrencyError);});
