/**
 * File: tests/observability/alerts.test.ts
 * Purpose: Verifies metric alert thresholds, tenant scoping, cooldown behavior, and notification outcomes.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { AdapterRegistry } from '../../packages/core/src/adapter-registry';
import { NotificationService } from '../../packages/notifications/src';
import { AlertEngine,InMemoryAlertStateStore } from '../../packages/observability/src';
const resource={serviceName:'worker'};
function point(value:number,org='o1'){return{id:`m-${value}-${org}`,timestamp:new Date().toISOString(),name:'worker.offline.count',kind:'gauge' as const,value,resource,scope:{organizationId:org},correlationId:'corr'};}
test('alert engine triggers matching tenant-scoped rules and dispatches notification',async()=>{const registry=new AdapterRegistry();let calls=0;registry.register({descriptor:{id:'notify',kind:'notification',version:'1',displayName:'n',description:'n',capabilities:['notify']},async health(){return{status:'healthy' as const,checkedAt:new Date().toISOString()};},async execute(){calls++;return{ok:true,externalId:'x'};}} as any);const state=new InMemoryAlertStateStore();const engine=new AlertEngine([{id:'offline',name:'Workers offline',metric:'worker.offline.count',operator:'gt',threshold:0,severity:'critical',cooldownSeconds:60,notificationAdapterIds:['notify'],scope:{organizationId:'o1'}}],state,new NotificationService(registry));const alerts=await engine.evaluate(point(2));assert.equal(alerts.length,1);assert.equal(alerts[0]?.status,'notified');assert.equal(calls,1);});
test('alert cooldown suppresses duplicate triggers',async()=>{const state=new InMemoryAlertStateStore();const engine=new AlertEngine([{id:'offline',name:'Workers offline',metric:'worker.offline.count',operator:'gt',threshold:0,severity:'warning',cooldownSeconds:60,notificationAdapterIds:[]}],state);assert.equal((await engine.evaluate(point(2))).length,1);assert.equal((await engine.evaluate(point(3))).length,0);});
test('tenant-scoped alert rule does not fire for another organization',async()=>{const state=new InMemoryAlertStateStore();const engine=new AlertEngine([{id:'offline',name:'Workers offline',metric:'worker.offline.count',operator:'gt',threshold:0,severity:'warning',cooldownSeconds:0,notificationAdapterIds:[],scope:{organizationId:'o1'}}],state);assert.equal((await engine.evaluate(point(2,'o2'))).length,0);});
test('notification failures are captured without losing the alert record',async()=>{const registry=new AdapterRegistry();registry.register({descriptor:{id:'bad',kind:'notification',version:'1',displayName:'bad',description:'bad',capabilities:['notify']},async health(){return{status:'healthy' as const,checkedAt:new Date().toISOString()};},async execute(){throw new Error('delivery failed');}} as any);const state=new InMemoryAlertStateStore();const engine=new AlertEngine([{id:'r',name:'Rule',metric:'worker.offline.count',operator:'gte',threshold:1,severity:'critical',cooldownSeconds:0,notificationAdapterIds:['bad']}],state,new NotificationService(registry));const [alert]=await engine.evaluate(point(1));assert.equal(alert?.status,'notification_failed');assert.equal((await state.list())[0]?.status,'notification_failed');});
