/**
 * File: tests/distributed/worker-agent.test.ts
 * Purpose: Verifies worker-agent execution through runner adapters, successful completion, retry behavior, and non-runner adapter rejection.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';import { AdapterRegistry } from '../../packages/core/src/adapter-registry';import { DistributedExecutionCoordinator } from '../../packages/distributed/src/coordinator';import { InMemoryDistributedExecutionQueue } from '../../packages/distributed/src/in-memory-queue';import { DistributedWorkerAgent } from '../../packages/distributed/src/worker-agent';
const scope={organizationId:'o1',projectId:'p1'};
async function setup(execute:(request:any)=>Promise<any>,kind:'runner'|'runtime'='runner'){const q=new InMemoryDistributedExecutionQueue();const c=new DistributedExecutionCoordinator(q);const worker=await c.registerWorker({id:'w1',scope,capabilities:{languages:['python'],runners:['pytest']},maxConcurrency:1});const registry=new AdapterRegistry();registry.register({descriptor:{id:'runner.pytest',kind,version:'1',displayName:'Pytest',description:'test',capabilities:[]},async health(){return{status:'healthy' as const,checkedAt:new Date().toISOString()};},id:'runner.pytest',capabilities(){return{discovery:false,cancellation:false,sharding:false,retries:false,tags:false,junitOutput:true};},execute} as any);return{q,c,worker,registry};}
test('worker agent leases and completes a job using the registered runner adapter',async()=>{const s=await setup(async(request)=>({runId:request.runId,status:'passed',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString()}));const job=await s.c.enqueue({scope,request:{runId:'r1',projectId:'p1',runtime:{language:'python',runner:'pytest'}}});const agent=new DistributedWorkerAgent(s.worker,s.q,s.registry);const result=await agent.processOne();assert.equal(result.processed,true);assert.equal((await s.q.getJob(job.id))?.state,'succeeded');});
test('worker agent requeues retryable runner exceptions',async()=>{const s=await setup(async()=>{throw new Error('runner unavailable');});const job=await s.c.enqueue({scope,maxAttempts:2,request:{runId:'r1',projectId:'p1',runtime:{language:'python',runner:'pytest'}}});const agent=new DistributedWorkerAgent(s.worker,s.q,s.registry,{leaseMs:1000,workerStaleMs:60_000,retryDelayMs:0});await agent.processOne();const stored=await s.q.getJob(job.id);assert.equal(stored?.state,'queued');assert.equal(stored?.failure?.message,'runner unavailable');});
test('worker agent rejects adapters registered under a non-runner kind',async()=>{const s=await setup(async()=>({}),'runtime');const job=await s.c.enqueue({scope,maxAttempts:1,request:{runId:'r1',projectId:'p1',runtime:{language:'python',runner:'pytest'}}});const agent=new DistributedWorkerAgent(s.worker,s.q,s.registry,{leaseMs:1000,workerStaleMs:60_000,retryDelayMs:0});await agent.processOne();assert.equal((await s.q.getJob(job.id))?.state,'dead-letter');});
test('worker agent keeps the lease alive during a longer execution',async()=>{const s=await setup(async(request)=>{await new Promise(resolve=>setTimeout(resolve,60));return{runId:request.runId,status:'passed',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString()};});const job=await s.c.enqueue({scope,request:{runId:'r-long',projectId:'p1',runtime:{language:'python',runner:'pytest'}}});const agent=new DistributedWorkerAgent(s.worker,s.q,s.registry,{leaseMs:20,workerStaleMs:60_000,retryDelayMs:0,heartbeatMs:5});const result=await agent.processOne();assert.equal(result.state,'succeeded');assert.equal((await s.q.getJob(job.id))?.state,'succeeded');});
