/**
 * File: packages/agent/src/runtime.ts
 * Purpose: Runs the standalone execution-agent registration, polling, concurrency, heartbeat, drain, telemetry, and graceful-shutdown lifecycle.
 * Author: Raushan Raj
 */
import type { AdapterRegistry } from '../../core/src/adapter-registry';
import { createId } from '../../core/src/ids';
import type { WorkerCapabilities,WorkerRegistration,WorkerState } from '../../contracts/src/distributed';
import type { TenantScope } from '../../contracts/src/governance';
import { DistributedWorkerAgent } from '../../distributed/src/worker-agent';
import type { AgentControlPlaneClient } from './control-plane-client';
import type { ExecutionAgentLifecycle } from './lifecycle';
export interface ExecutionAgentRuntimeOptions { pollMs:number; heartbeatMs:number; leaseMs:number; workerStaleMs:number; retryDelayMs:number; shutdownGraceMs:number; }
export interface ExecutionAgentSnapshot { workerId:string; state:WorkerState|'starting'|'stopped'; registered:boolean; ready:boolean; activeJobs:number; startedAt?:string; lastHeartbeatAt?:string; lastError?:string; }
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
export class ExecutionAgentRuntime{
  private registration?:WorkerRegistration;private state:WorkerState|'starting'|'stopped'='stopped';private stopping=false;private active=0;private startedAt?:string;private lastHeartbeatAt?:string;private lastError?:string;private loopPromise?:Promise<void>;
  constructor(private readonly workerId:string,private readonly scope:TenantScope,private readonly capabilities:WorkerCapabilities,private readonly metadata:Record<string,string>,private readonly maxConcurrency:number,private readonly client:AgentControlPlaneClient,private readonly registry:AdapterRegistry,private readonly lifecycle:ExecutionAgentLifecycle,private readonly options:ExecutionAgentRuntimeOptions){}
  snapshot():ExecutionAgentSnapshot{return{workerId:this.workerId,state:this.state,registered:Boolean(this.registration),ready:Boolean(this.registration)&&this.state==='online'&&!this.stopping&&this.capabilities.runners.length>0,activeJobs:this.active,startedAt:this.startedAt,lastHeartbeatAt:this.lastHeartbeatAt,lastError:this.lastError};}
  async start():Promise<void>{if(this.loopPromise)return;this.stopping=false;this.state='starting';this.startedAt=new Date().toISOString();this.registration=await this.client.registerWorker({id:this.workerId,scope:this.scope,capabilities:this.capabilities,maxConcurrency:this.maxConcurrency,state:'online',registeredAt:this.startedAt,heartbeatAt:this.startedAt,activeLeases:0,metadata:this.metadata});this.state='online';this.lastHeartbeatAt=new Date().toISOString();await this.telemetry('healthy','Execution agent registered.');this.loopPromise=this.loop();}
  async drain():Promise<void>{if(this.state==='stopped')return;this.state='draining';try{await this.client.heartbeatWorker(this.workerId,new Date().toISOString(),'draining');this.lastHeartbeatAt=new Date().toISOString();}catch(error){this.lastError=error instanceof Error?error.message:'Agent drain heartbeat failed.';}await this.telemetry('degraded','Execution agent is draining.');}
  async stop():Promise<void>{if(this.state==='stopped')return;this.stopping=true;await this.drain();const deadline=Date.now()+this.options.shutdownGraceMs;while(this.active>0&&Date.now()<deadline)await sleep(25);this.state='stopped';await this.telemetry('unavailable',this.active>0?'Execution agent stopped with active work after grace timeout.':'Execution agent stopped.');if(this.loopPromise){await this.loopPromise;this.loopPromise=undefined;}}
  private async loop():Promise<void>{let nextHeartbeat=0;while(!this.stopping){const now=Date.now();if(now>=nextHeartbeat){try{await this.client.heartbeatWorker(this.workerId,new Date().toISOString(),this.state==='starting'?'online':this.state as WorkerState);this.lastHeartbeatAt=new Date().toISOString();this.lastError=undefined;}catch(error){this.lastError=error instanceof Error?error.message:'Agent heartbeat failed.';}nextHeartbeat=now+this.options.heartbeatMs;}if(this.state==='online'&&this.active<this.maxConcurrency){const slots=this.maxConcurrency-this.active;for(let i=0;i<slots;i++)this.launchOne();}await sleep(this.options.pollMs);} }
  private launchOne():void{this.active+=1;const worker=this.registration!;const agent=new DistributedWorkerAgent({...worker,state:'online'},this.client,this.registry,{leaseMs:this.options.leaseMs,workerStaleMs:this.options.workerStaleMs,retryDelayMs:this.options.retryDelayMs,heartbeatMs:Math.max(1_000,Math.floor(this.options.leaseMs/3)),heartbeatWorkerBeforeLease:false},this.lifecycle);void agent.processOne().then(result=>{if(result.processed)void this.client.emitMetric({id:createId('metric'),timestamp:new Date().toISOString(),name:'qualyntra.agent.jobs.processed',kind:'counter',value:1,resource:{serviceName:'qualyntra-agent',instanceId:this.workerId},attributes:{state:result.state??'unknown'}}).catch(()=>{});}).catch(error=>{this.lastError=error instanceof Error?error.message:'Agent execution loop failed.';}).finally(()=>{this.active=Math.max(0,this.active-1);});}
  private async telemetry(status:'healthy'|'degraded'|'unavailable',message:string):Promise<void>{try{await this.client.emitHealth({id:createId('health'),timestamp:new Date().toISOString(),component:`execution-agent:${this.workerId}`,status,correlationId:createId('corr'),message,attributes:{activeJobs:this.active,state:this.state}});}catch{}}
}
