/**
 * File: apps/dashboard/web/ui.ts
 * Purpose: Renders accessible dashboard pages with DOM APIs and textContent so server-provided values are never interpreted as HTML.
 * Author: Raushan Raj
 */
import type {AdapterDescriptor,AuditRecord,DashboardApiClient,EvaluationRecord,ObservabilitySummary,Page,RunRecord,TenantScope} from './api.js';
import {DashboardApiError} from './api.js';

export type Route='overview'|'observability'|'runs'|'evaluations'|'releases'|'workers'|'artifacts'|'audit'|'integrations'|'settings';
export const ROUTES:ReadonlyArray<{id:Route;label:string;hint:string}>=[
  {id:'overview',label:'Overview',hint:'Quality health'},{id:'observability',label:'Observability',hint:'Telemetry and alerts'},{id:'runs',label:'Runs',hint:'Execution history'},{id:'evaluations',label:'AI Evaluation',hint:'LLM and RAG quality'},{id:'releases',label:'Releases',hint:'Policy decisions'},{id:'workers',label:'Workers',hint:'Execution capacity'},{id:'artifacts',label:'Artifacts',hint:'Evidence storage'},{id:'integrations',label:'Integrations',hint:'Delivery systems'},{id:'audit',label:'Audit',hint:'Governance history'},{id:'settings',label:'Settings',hint:'Platform configuration'}
];
function el<K extends keyof HTMLElementTagNameMap>(name:K,className?:string,text?:string):HTMLElementTagNameMap[K]{const node=document.createElement(name);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function badge(value:string):HTMLElement{const span=el('span',`badge ${value.toLowerCase()}`,value);return span;}
function fmt(value:string|undefined):string{if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString();}
function pageHead(title:string,description:string):HTMLElement{const wrap=el('div','page-head');const copy=el('div');copy.append(el('h1',undefined,title),el('p',undefined,description));wrap.append(copy);return wrap;}
function panel(title:string):{root:HTMLElement;body:HTMLElement}{const root=el('section','panel');const head=el('div','panel-head');head.append(el('h2',undefined,title));const body=el('div');root.append(head,body);return{root,body};}
function errorNode(error:unknown):HTMLElement{const message=error instanceof DashboardApiError?`${error.message}${error.correlationId?` Correlation: ${error.correlationId}`:''}`:error instanceof Error?error.message:'Unexpected dashboard error.';return el('div','error-box',message);}
function table(headers:string[],rows:Array<Array<string|HTMLElement>>):HTMLElement{const wrap=el('div','table-wrap');const t=el('table');const thead=el('thead');const hr=el('tr');for(const h of headers)hr.append(el('th',undefined,h));thead.append(hr);const tbody=el('tbody');for(const row of rows){const tr=el('tr');for(const cell of row){const td=el('td');td.append(typeof cell==='string'?document.createTextNode(cell):cell);tr.append(td);}tbody.append(tr);}t.append(thead,tbody);wrap.append(t);return wrap;}

export function createShell(root:HTMLElement,input:{scope:TenantScope;authenticated:boolean;actorId?:string;onScope:(scope:TenantScope)=>void;onRoute:(route:Route)=>void}){
  root.replaceChildren();root.removeAttribute('aria-busy');const sidebar=el('aside','sidebar');const brand=el('div','brand');brand.append(el('div','brand-mark'));const brandCopy=el('div');brandCopy.append(el('strong',undefined,'Qualyntra'),el('small',undefined,'Quality intelligence'));brand.append(brandCopy);const nav=el('nav');nav.setAttribute('aria-label','Primary navigation');for(const item of ROUTES){const a=el('a');a.href=`#/${item.id}`;a.dataset.route=item.id;a.append(el('span',undefined,item.label));a.title=item.hint;nav.append(a);}sidebar.append(brand,nav);
  const workspace=el('div','workspace');const top=el('header','topbar');const scopeGrid=el('div','scope-grid');const fields:Array<[keyof TenantScope,string]>=[['organizationId','Organization'],['workspaceId','Workspace'],['projectId','Project'],['environmentId','Environment']];for(const [key,label] of fields){const field=el('div','field');const id=`scope-${key}`;const l=el('label',undefined,label);l.htmlFor=id;const i=el('input');i.id=id;i.value=input.scope[key]??'';i.autocomplete='off';i.addEventListener('change',()=>{const next={...input.scope,[key]:i.value.trim()};input.scope=next;input.onScope(next);});field.append(l,i);scopeGrid.append(field);}const status=el('div',`status-pill ${input.authenticated?'ok':'bad'}`,input.authenticated?`Session: ${input.actorId??'authenticated'}`:'Session required');status.setAttribute('role','status');top.append(scopeGrid,status);const main=el('main');main.id='main-content';main.tabIndex=-1;const live=el('div');live.id='dashboard-live';live.setAttribute('aria-live','polite');live.className='muted';workspace.append(top,main,live);root.append(sidebar,workspace);
  const activate=(route:Route)=>{for(const a of nav.querySelectorAll('a')){if((a as HTMLElement).dataset.route===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}input.onRoute(route);};
  nav.addEventListener('click',event=>{const target=(event.target as HTMLElement).closest('a');if(!target)return;const route=(target as HTMLElement).dataset.route as Route|undefined;if(route)activate(route);});
  return{main,live,activate};
}

export async function renderRoute(main:HTMLElement,live:HTMLElement,route:Route,api:DashboardApiClient):Promise<void>{
  main.replaceChildren(pageHead(ROUTES.find(item=>item.id===route)?.label??'Dashboard',description(route)),el('div','loading','Loading…'));live.textContent=`Loading ${route}`;
  try{switch(route){case'overview':await overview(main,api);break;case'observability':await observability(main,api);break;case'runs':await runs(main,api);break;case'evaluations':await evaluations(main,api);break;case'releases':await releases(main,api);break;case'workers':await workers(main,api);break;case'artifacts':artifacts(main);break;case'audit':await audit(main,api);break;case'integrations':await integrations(main,api);break;case'settings':await settings(main,api);break;}live.textContent=`${route} loaded`;main.focus();}catch(error){const loading=main.querySelector('.loading');loading?.remove();main.append(errorNode(error));live.textContent=`${route} failed to load`;}
}
function description(route:Route):string{return({overview:'Release, execution, evaluation, integration, and governance signals in one tenant-aware view.',observability:'Review tenant-scoped telemetry volume, component health, recent alerts, and available notification delivery adapters.',runs:'Inspect normalized execution requests and their current lifecycle state.',evaluations:'Review queued and completed AI, LLM, RAG, and agent evaluation records.',releases:'Retrieve evidence-backed release decisions without bypassing governance.',workers:'Inspect runtime capability signals while distributed worker APIs remain isolated behind the control plane.',artifacts:'Evidence storage is available in the platform; dashboard metadata APIs will be exposed through the control plane rather than direct storage access.',audit:'Review tenant-scoped immutable governance events.',integrations:'Inspect registered enterprise integration adapters without exposing their credentials.',settings:'Read platform capabilities, runtimes, providers, policies, and adapter descriptors.'} as Record<Route,string>)[route];}
function clearLoading(main:HTMLElement):void{main.querySelector('.loading')?.remove();}
async function overview(main:HTMLElement,api:DashboardApiClient):Promise<void>{const [runsR,evalsR,intR,auditR]=await Promise.allSettled([api.get<Page<RunRecord>>('/runs?limit=20'),api.get<Page<EvaluationRecord>>('/evaluations?limit=20'),api.get<{items:AdapterDescriptor[]}>('/integrations'),api.get<{items:AuditRecord[];total:number}>('/audit?limit=20')]);clearLoading(main);const cards=el('div','grid');const values=[['Runs',runsR.status==='fulfilled'?String(runsR.value.total):'—'],['Evaluations',evalsR.status==='fulfilled'?String(evalsR.value.total):'—'],['Integrations',intR.status==='fulfilled'?String(intR.value.items.length):'—'],['Audit events',auditR.status==='fulfilled'?String(auditR.value.total):'—']];for(const [label,value] of values){const card=el('section','card');card.append(el('div','eyebrow',label),el('div','metric',value));cards.append(card);}main.append(cards);if(runsR.status==='fulfilled'){const p=panel('Recent runs');p.body.append(runsTable(runsR.value.items.slice(0,8)));main.append(p.root);}for(const result of [runsR,evalsR,intR,auditR])if(result.status==='rejected')main.append(errorNode(result.reason));}
async function observability(main:HTMLElement,api:DashboardApiClient):Promise<void>{const [summary,notifications]=await Promise.all([api.get<ObservabilitySummary>('/observability/summary'),api.get<{items:AdapterDescriptor[]}>('/notifications')]);clearLoading(main);const cards=el('div','grid');for(const [label,value] of [['Logs',String(summary.counts.logs)],['Metrics',String(summary.counts.metrics)],['Spans',String(summary.counts.spans)],['Alerts',String(summary.counts.alerts)],['Healthy',String(summary.health.healthy)],['Unavailable',String(summary.health.unavailable)]]){const card=el('section','card');card.append(el('div','eyebrow',label),el('div','metric',value));cards.append(card);}main.append(cards);const alertPanel=panel('Recent alerts');alertPanel.body.append(summary.latestAlerts.length?table(['Severity','Rule','Metric','Observed','Status','Triggered'],summary.latestAlerts.map(item=>[badge(item.severity),item.ruleName,item.metric,String(item.observedValue),badge(item.status),fmt(item.triggeredAt)])):el('div','empty','No alerts have been triggered for the selected tenant scope.'));const notifyPanel=panel('Notification adapters');notifyPanel.body.append(notifications.items.length?table(['Adapter','Version','Capabilities'],notifications.items.map(item=>[item.displayName??item.id,item.version??'—',(item.capabilities??[]).join(', ')||'—'])):el('div','empty','No notification adapters are registered in this control-plane process.'));main.append(alertPanel.root,notifyPanel.root);}
function runsTable(items:RunRecord[]):HTMLElement{return items.length?table(['Run','Status','Runtime','Updated'],items.map(run=>[run.id,badge(run.status),[run.request?.runtime?.language,run.request?.runtime?.runner,run.request?.runtime?.engine].filter(Boolean).join(' / ')||'—',fmt(run.updatedAt)])):el('div','empty','No runs found for the selected tenant scope.');}
async function runs(main:HTMLElement,api:DashboardApiClient):Promise<void>{const data=await api.get<Page<RunRecord>>('/runs?limit=100');clearLoading(main);const p=panel(`Runs (${data.total})`);p.body.append(runsTable(data.items));main.append(p.root);}
async function evaluations(main:HTMLElement,api:DashboardApiClient):Promise<void>{const data=await api.get<Page<EvaluationRecord>>('/evaluations?limit=100');clearLoading(main);const p=panel(`Evaluations (${data.total})`);p.body.append(data.items.length?table(['Evaluation','Profile','Dataset','Status','Updated'],data.items.map(item=>[item.id,item.profileId,item.datasetId,badge(item.status),fmt(item.updatedAt)])):el('div','empty','No evaluations found for the selected tenant scope.'));main.append(p.root);}
async function releases(main:HTMLElement,api:DashboardApiClient):Promise<void>{clearLoading(main);const notice=el('div','notice','Enter a release identifier to retrieve its evidence-backed policy decision. No release decision is synthesized in the browser.');const toolbar=el('div','toolbar');toolbar.style.marginTop='1rem';const input=el('input');input.placeholder='Release ID';input.setAttribute('aria-label','Release ID');const button=el('button','button','Load decision');const output=el('div');button.addEventListener('click',()=>{const id=input.value.trim();if(!id)return;output.replaceChildren(el('div','loading','Loading…'));void api.get<any>(`/releases/${encodeURIComponent(id)}/decision`).then(value=>{const p=panel('Release decision');const list=el('div','list');for(const [key,val] of Object.entries(value?.decision??value??{})){const item=el('div','list-item');item.append(el('strong',undefined,key),el('div','muted',typeof val==='string'?val:JSON.stringify(val)));list.append(item);}p.body.append(list);output.replaceChildren(p.root);}).catch(error=>output.replaceChildren(errorNode(error)));});toolbar.append(input,button);main.append(notice,toolbar,output);}
async function workers(main:HTMLElement,api:DashboardApiClient):Promise<void>{const data=await api.get<{items:AdapterDescriptor[]}>('/runtimes');clearLoading(main);const p=panel('Runtime capability surface');p.body.append(data.items.length?table(['Runtime adapter','Kind','Version','Capabilities'],data.items.map(item=>[item.displayName??item.id,item.kind,item.version??'—',(item.capabilities??[]).join(', ')||'—'])):el('div','empty','No runtime adapters are registered in this control-plane process.'));main.append(p.root,el('div','notice','Worker registration, lease, and heartbeat data remain behind the distributed execution boundary until dedicated tenant-authorized control-plane endpoints are published. The dashboard does not connect directly to workers.'));}
function artifacts(main:HTMLElement):void{clearLoading(main);main.append(el('div','notice','Artifact storage is intentionally not queried directly from the browser. A future control-plane artifact metadata endpoint will expose tenant-authorized evidence records and short-lived download grants while keeping S3/Azure/local credentials server-side.'));}
async function audit(main:HTMLElement,api:DashboardApiClient):Promise<void>{const data=await api.get<{items:AuditRecord[];total:number}>('/audit?limit=100');clearLoading(main);const p=panel(`Audit events (${data.total})`);p.body.append(data.items.length?table(['Time','Actor','Action','Resource','Outcome'],data.items.map(item=>[fmt(item.timestamp),item.actorId,item.action,item.resource,badge(item.outcome)])):el('div','empty','No audit records found for this scope.'));main.append(p.root);}
async function integrations(main:HTMLElement,api:DashboardApiClient):Promise<void>{const data=await api.get<{items:AdapterDescriptor[]}>('/integrations');clearLoading(main);const p=panel('Registered integrations');p.body.append(data.items.length?table(['Adapter','Kind','Version','Capabilities'],data.items.map(item=>[item.displayName??item.id,item.kind,item.version??'—',(item.capabilities??[]).join(', ')||'—'])):el('div','empty','No integration adapters are registered in this control-plane process.'));main.append(p.root);}
async function settings(main:HTMLElement,api:DashboardApiClient):Promise<void>{const [cap,runtimes,providers,policies]=await Promise.all([api.get<any>('/capabilities'),api.get<{items:AdapterDescriptor[]}>('/runtimes'),api.get<{items:AdapterDescriptor[]}>('/providers'),api.get<Page<any>>('/policies?limit=100')]);clearLoading(main);const cards=el('div','grid');for(const [label,value] of [['API version',cap.apiVersion??'—'],['Runtime adapters',String(runtimes.items.length)],['Model providers',String(providers.items.length)],['Policies',String(policies.total)]]){const card=el('section','card');card.append(el('div','eyebrow',label),el('div','metric',value));cards.append(card);}main.append(cards);}
