/**
 * File: adapters/llm/bedrock/src/index.ts
 * Purpose: Implements Amazon Bedrock Converse text generation with bearer-token or pluggable signed-header authentication and injectable transport.
 * Author: Raushan Raj
 */
import type { ModelProviderAdapter,ModelProviderCapabilities,ModelRequest,ModelResponse } from '../../../../packages/contracts/src/evaluation';
import type { NetworkPolicy } from '../../../../packages/contracts/src/configuration';
import { assertNetworkAllowed } from '../../../../packages/security/src/network-policy';
import { asRecord,FetchProviderHttpTransport,type ProviderHttpTransport } from '../../../../packages/providers/src/http';
import { capabilitiesWith,configuredHealth,endpoint,header,TEXT_CHAT_CAPABILITIES } from '../../../../packages/providers/src/adapter-utils';
export interface BedrockAuthContext{method:'POST';url:string;headers:Record<string,string>;body:string;}
export type BedrockHeaderSigner=(context:BedrockAuthContext)=>Promise<Record<string,string>>|Record<string,string>;
export interface BedrockOptions{id?:string;baseUrl:string;bearerToken?:string;signHeaders?:BedrockHeaderSigner;model:string;networkPolicy:NetworkPolicy;headers?:Record<string,string>;timeoutMs?:number;transport?:ProviderHttpTransport;capabilities?:Partial<ModelProviderCapabilities>;}
export class BedrockProvider implements ModelProviderAdapter{readonly id:string;private readonly transport:ProviderHttpTransport;constructor(private readonly options:BedrockOptions){this.id=options.id??'bedrock';if(options.bearerToken&&options.signHeaders)throw new Error('Configure either Bedrock bearer token or signed-header callback, not both.');this.transport=options.transport??new FetchProviderHttpTransport();}capabilities(){return capabilitiesWith(TEXT_CHAT_CAPABILITIES,this.options.capabilities);}health(){return Promise.resolve(configuredHealth(this.options.baseUrl,this.options.networkPolicy,Boolean(this.options.bearerToken||this.options.signHeaders),'Bedrock authentication is not configured.'));}async generate(request:ModelRequest):Promise<ModelResponse>{assertNetworkAllowed(this.options.baseUrl,this.options.networkPolicy);const started=Date.now();const model=request.model??this.options.model;const url=endpoint(this.options.baseUrl,`/model/${encodeURIComponent(model)}/converse`);const system=request.messages.filter(m=>m.role==='system').map(m=>({text:m.content}));const messages=request.messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'assistant':'user',content:[{text:m.content}]}));const bodyText=JSON.stringify({messages,...(system.length?{system}:{}),inferenceConfig:{...(request.maxTokens===undefined?{}:{maxTokens:request.maxTokens}),...(request.temperature===undefined?{}:{temperature:request.temperature})}});let headers:Record<string,string>={'content-type':'application/json',...this.options.headers};if(this.options.bearerToken)headers.authorization=`Bearer ${this.options.bearerToken}`;if(this.options.signHeaders)headers={...headers,...await this.options.signHeaders({method:'POST',url,headers:{...headers},body:bodyText})};const response=await this.transport.request({providerId:this.id,url,method:'POST',headers,body:bodyText,timeoutMs:request.timeoutMs??this.options.timeoutMs});const body=asRecord(response.body);const output=asRecord(asRecord(body.output).message);const text=(Array.isArray(output.content)?output.content:[]).map(part=>asRecord(part).text).filter((v):v is string=>typeof v==='string').join('');const usage=asRecord(body.usage);const inputTokens=num(usage.inputTokens);const outputTokens=num(usage.outputTokens);return{content:text,model,provider:this.id,latencyMs:num(asRecord(body.metrics).latencyMs)??(Date.now()-started),inputTokens,outputTokens,totalTokens:num(usage.totalTokens)??((inputTokens??0)+(outputTokens??0)),requestId:header(response.headers,'x-amzn-requestid','x-request-id','request-id'),raw:body};}}
function num(value:unknown):number|undefined{return typeof value==='number'&&Number.isFinite(value)?value:undefined;}
