/**
 * File: tests/identity/oidc-verifier.test.ts
 * Purpose: Verifies strict OIDC discovery, JWKS rotation, JWT signature, algorithm, audience, and temporal claim enforcement.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';
import { generateKeyPairSync,sign } from 'node:crypto';
import { OidcMetadataResolver,OidcJwtVerifier } from '../../packages/identity/src';
import { FakeIdentityTransport,audience,claims,issuer,providerConfig,publicJwk,signedToken } from './helpers';

function verifier(transport=new FakeIdentityTransport(),config={...providerConfig}){const resolver=new OidcMetadataResolver(config,transport,{allowNetwork:true,allowedHosts:['issuer.example']});return{verifier:new OidcJwtVerifier(config,resolver),resolver,transport};}

test('OIDC verifier accepts an allowlisted RS256 token with issuer audience and lifetime checks',async()=>{const x=verifier();const result=await x.verifier.verify(signedToken(claims()));assert.equal(result.issuer,issuer);assert.equal(result.subject,'user-1');assert.deepEqual(result.audiences,[audience]);assert.equal(result.tokenId,'token-1');});
test('OIDC verifier rejects wrong audience, expired tokens, unapproved algorithms, and token-controlled key URLs',async()=>{const x=verifier();await assert.rejects(()=>x.verifier.verify(signedToken(claims({aud:'other'}))),/audience/);await assert.rejects(()=>x.verifier.verify(signedToken(claims({exp:1}))),/expired/);const unsecured=`${Buffer.from(JSON.stringify({alg:'none',kid:'key-1'})).toString('base64url')}.${Buffer.from(JSON.stringify(claims())).toString('base64url')}.x`;await assert.rejects(()=>x.verifier.verify(unsecured),/algorithm/);await assert.rejects(()=>x.verifier.verify(signedToken(claims(),{alg:'RS256',kid:'key-1',jku:'https://attacker.invalid/keys'})),/key URLs/);});
test('OIDC discovery rejects issuer substitution and network policy blocks non-allowlisted JWKS hosts',async()=>{const mismatch=verifier(new FakeIdentityTransport('https://evil.example'));await assert.rejects(()=>mismatch.resolver.discovery(),/issuer/);const transport=new FakeIdentityTransport();const resolver=new OidcMetadataResolver(providerConfig,transport,{allowNetwork:true,allowedHosts:['different.example']});await assert.rejects(()=>resolver.discovery(),/allowlisted/);});
test('unknown signing kid triggers one JWKS refresh and supports key rotation',async()=>{const next=generateKeyPairSync('rsa',{modulusLength:2048,publicExponent:0x10001});const nextJwk={...(next.publicKey.export({format:'jwk'}) as any),kid:'rotated',use:'sig',alg:'RS256'};class Rotating extends FakeIdentityTransport{override async get(request:any){if(request.url.includes('.well-known'))return super.get(request);this.jwksCalls++;this.calls.push(request.url);return{status:200,headers:{},body:{keys:this.jwksCalls===1?[publicJwk]:[nextJwk]}};}}const transport=new Rotating();const x=verifier(transport);const now=Math.floor(Date.now()/1000),payload=claims({iat:now-1,exp:now+60});const head=Buffer.from(JSON.stringify({alg:'RS256',kid:'rotated',typ:'JWT'})).toString('base64url'),body=Buffer.from(JSON.stringify(payload)).toString('base64url'),input=`${head}.${body}`,sig=sign('RSA-SHA256',Buffer.from(input),next.privateKey).toString('base64url');assert.equal((await x.verifier.verify(`${input}.${sig}`)).subject,'user-1');assert.equal(transport.jwksCalls,2);});

test('OIDC verifier supports explicitly allowlisted ES256 with P-256 keys',async()=>{const pair=generateKeyPairSync('ec',{namedCurve:'P-256'});const jwk={...(pair.publicKey.export({format:'jwk'}) as any),kid:'ec-1',use:'sig',alg:'ES256'};const transport=new FakeIdentityTransport(issuer,[jwk]);const config={...providerConfig,allowedAlgorithms:['ES256'] as const};const resolver=new OidcMetadataResolver(config as any,transport,{allowNetwork:true,allowedHosts:['issuer.example']});const x=new OidcJwtVerifier(config as any,resolver);const head=Buffer.from(JSON.stringify({alg:'ES256',kid:'ec-1',typ:'jwt'})).toString('base64url'),body=Buffer.from(JSON.stringify(claims())).toString('base64url'),input=`${head}.${body}`,sig=sign('sha256',Buffer.from(input),{key:pair.privateKey,dsaEncoding:'ieee-p1363'} as any).toString('base64url');assert.equal((await x.verify(`${input}.${sig}`)).subject,'user-1');});

test('maximum token age requires iat instead of silently disabling the age policy',async()=>{const transport=new FakeIdentityTransport();const config={...providerConfig,maxTokenAgeSeconds:120};const resolver=new OidcMetadataResolver(config,transport,{allowNetwork:true,allowedHosts:['issuer.example']});const x=new OidcJwtVerifier(config,resolver);const withoutIat=claims();delete withoutIat.iat;await assert.rejects(()=>x.verify(signedToken(withoutIat)),/iat claim is required/);});
