/**
 * File: adapters/llm/openai-compatible/src/index.ts
 * Purpose: Connects to OpenAI-compatible chat-completions endpoints with explicit network-policy enforcement and environment-supplied credentials.
 * Author: Raushan Raj
 */
import type { ModelProviderAdapter,ModelProviderCapabilities,ModelRequest,ModelResponse } from '../../../../packages/contracts/src/evaluation'; import type { NetworkPolicy } from '../../../../packages/contracts/src/configuration'; import { assertNetworkAllowed } from '../../../../packages/security/src/network-policy';
export interface OpenAICompatibleOptions { id:string;baseUrl:string;apiKey?:string;model:string;networkPolicy:NetworkPolicy;headers?:Record<string,string>; }
export class OpenAICompatibleProvider implements ModelProviderAdapter { readonly id:string; constructor(private readonly options:OpenAICompatibleOptions){this.id=options.id;} capabilities():ModelProviderCapabilities{return {chat:true,streaming:false,embeddings:false,jsonMode:true,tools:true,multimodal:false};} async health(){try{assertNetworkAllowed(this.options.baseUrl,this.options.networkPolicy);return {status:'healthy' as const,message:'Network policy permits configured endpoint.'};}catch(e){return {status:'unavailable' as const,message:e instanceof Error?e.message:String(e)};}} async generate(request:ModelRequest):Promise<ModelResponse>{assertNetworkAllowed(this.options.baseUrl,this.options.networkPolicy);const start=Date.now();const url=new URL('/v1/chat/completions',this.options.baseUrl).toString();const headers:Record<string,string>={'content-type':'application/json',...this.options.headers};if(this.options.apiKey)headers.authorization=`Bearer ${this.options.apiKey}`;const response=await fetch(url,{method:'POST',headers,body:JSON.stringify({model:request.model??this.options.model,messages:request.messages,temperature:request.temperature,max_tokens:request.maxTokens})});if(!response.ok)throw new Error(`Provider ${this.id} returned HTTP ${response.status}`);const body:any=await response.json();return {content:String(body?.choices?.[0]?.message?.content??''),model:String(body?.model??request.model??this.options.model),provider:this.id,latencyMs:Date.now()-start,inputTokens:body?.usage?.prompt_tokens,outputTokens:body?.usage?.completion_tokens,raw:body};} }

