/**
 * File: tests/agent/capabilities-secrets.test.ts
 * Purpose: Verifies adapter-derived agent capability discovery and ephemeral execution secret materialization.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';import { promises as fs } from 'node:fs';import path from 'node:path';import { tmpdir } from 'node:os';import { AdapterRegistry } from '../../packages/core/src/adapter-registry';import { AgentEnvironmentSecretResolver,AgentFileSecretResolver,discoverAgentCapabilities,materializeExecutionSecrets } from '../../packages/agent/src';
test('capability discovery advertises only available runner adapters',async()=>{const registry=new AdapterRegistry();registry.register({descriptor:{id:'runner.pytest',kind:'runner',version:'1',displayName:'pytest',description:'x',capabilities:[],supportedLanguages:['python']},async health(){return{status:'healthy' as const,checkedAt:new Date().toISOString()};}} as any);registry.register({descriptor:{id:'runner.offline',kind:'runner',version:'1',displayName:'offline',description:'x',capabilities:[],supportedLanguages:['java']},async health(){return{status:'unavailable' as const,checkedAt:new Date().toISOString()};}} as any);const result=await discoverAgentCapabilities(registry,{labels:['gpu'],engines:['selenium']});assert.deepEqual(result.capabilities.runners,['pytest']);assert.deepEqual(result.capabilities.languages,['python']);assert.deepEqual(result.capabilities.engines,['selenium']);assert.equal(result.capabilities.labels?.includes('gpu'),true);assert.ok(result.metadata.hostname);});
test('file secret resolver materializes refs only into ephemeral request env',async()=>{const dir=await fs.mkdtemp(path.join(tmpdir(),'qualyntra-agent-secret-'));try{await fs.writeFile(path.join(dir,'api-token'),'value-123',{mode:0o600});const request:any={runId:'r1',projectId:'p1',runtime:{language:'python',runner:'pytest'},secretRefs:{API_TOKEN:{provider:'agent-file',key:'api-token'}}};const materialized=await materializeExecutionSecrets(request,[new AgentFileSecretResolver(dir)]);assert.equal(materialized.env?.API_TOKEN,'value-123');assert.equal(request.env,undefined);assert.equal(materialized.secretRefs?.API_TOKEN?.key,'api-token');}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('secret materialization rejects raw persisted env and unsupported providers',async()=>{await assert.rejects(()=>materializeExecutionSecrets({runId:'r',projectId:'p',runtime:{language:'python',runner:'pytest'},env:{TOKEN:'raw'}} as any,[]),/must not contain/);await assert.rejects(()=>materializeExecutionSecrets({runId:'r',projectId:'p',runtime:{language:'python',runner:'pytest'},secretRefs:{TOKEN:{provider:'missing',key:'x'}}} as any,[]),/No execution-agent secret resolver/);});
test('environment secret resolver is explicit and validates missing values',async()=>{const key='QUALYNTRA_TEST_AGENT_SECRET';process.env[key]='abc';try{const result=await materializeExecutionSecrets({runId:'r',projectId:'p',runtime:{language:'python',runner:'pytest'},secretRefs:{TOKEN:{provider:'agent-env',key}}} as any,[new AgentEnvironmentSecretResolver()]);assert.equal(result.env?.TOKEN,'abc');}finally{delete process.env[key];}});
