/**
 * File: tests/agent/runtime-health.test.ts
 * Purpose: Verifies execution-agent registration, readiness, drain/shutdown state, and local health endpoint behavior.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';import { AdapterRegistry } from '../../packages/core/src/adapter-registry';import { ExecutionAgentRuntime,createExecutionAgentHealthServer } from '../../packages/agent/src';
const scope={organizationId:'o1'};
function client(){return{async registerWorker(worker:any){return worker;},async heartbeatWorker(id:string,_now:string,state?:string){return{id,scope,capabilities:{languages:['python'],runners:['pytest']},maxConcurrency:1,state:state??'online',registeredAt:'x',heartbeatAt:'x',activeLeases:0};},async leaseNext(){return undefined;},async heartbeatLease(){throw new Error('unused');},async markRunning(){throw new Error('unused');},async complete(){throw new Error('unused');},async fail(){throw new Error('unused');},async emitHealth(){return;},async emitMetric(){return;}} as any;}
test('execution agent becomes ready after registration and drains before stopping',async()=>{const runtime=new ExecutionAgentRuntime('worker_test',scope,{languages:['python'],runners:['pytest']},{hostname:'h'},1,client(),new AdapterRegistry(),{} as any,{pollMs:5,heartbeatMs:10,leaseMs:100,workerStaleMs:1000,retryDelayMs:0,shutdownGraceMs:100});await runtime.start();assert.equal(runtime.snapshot().ready,true);await runtime.drain();assert.equal(runtime.snapshot().state,'draining');assert.equal(runtime.snapshot().ready,false);await runtime.stop();assert.equal(runtime.snapshot().state,'stopped');});
test('health server returns liveness and readiness without secrets',async(t:any)=>{const runtime={snapshot:()=>({workerId:'worker_test',state:'online',registered:true,ready:true,activeJobs:0})} as any;const server=createExecutionAgentHealthServer(runtime);await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});t.after(()=>server.close());const address=server.address();const base=`http://127.0.0.1:${typeof address==='object'&&address?address.port:0}`;const health=await fetch(`${base}/health`);assert.equal(health.status,200);const ready=await fetch(`${base}/ready`);assert.equal(ready.status,200);const state=await fetch(`${base}/state`);assert.equal(state.status,404);});
