/**
 * File: tests/agent/workspace-lifecycle.test.ts
 * Purpose: Verifies isolated workspace confinement, disk limits, symlink rejection, cleanup, and lifecycle artifact publication.
 * Author: Raushan Raj
 */
import test from 'node:test';import assert from 'node:assert/strict';import { promises as fs } from 'node:fs';import path from 'node:path';import { tmpdir } from 'node:os';import { AgentWorkspaceManager,ExecutionAgentLifecycle } from '../../packages/agent/src';
test('workspace manager confines job paths and cleans completed jobs',async()=>{const root=await fs.mkdtemp(path.join(tmpdir(),'qualyntra-agent-work-'));try{const manager=new AgentWorkspaceManager(root,1024,true);const dir=await manager.prepare('job_abc');await fs.writeFile(path.join(dir,'result.txt'),'ok');assert.equal(await manager.assertWithinLimit('job_abc'),2);assert.throws(()=>manager.resolveResultFile('job_abc','../outside.txt'),/escapes/);await manager.cleanup('job_abc');await assert.rejects(()=>fs.stat(dir));}finally{await fs.rm(root,{recursive:true,force:true});}});
test('workspace manager rejects size overflow and symlinks',async()=>{const root=await fs.mkdtemp(path.join(tmpdir(),'qualyntra-agent-work-'));try{const manager=new AgentWorkspaceManager(root,4,false);const dir=await manager.prepare('job_size');await fs.writeFile(path.join(dir,'big.txt'),'12345');await assert.rejects(()=>manager.assertWithinLimit('job_size'),/size limit/);await fs.rm(dir,{recursive:true,force:true});await fs.mkdir(dir);await fs.symlink(root,path.join(dir,'link'));await assert.rejects(()=>manager.assertWithinLimit('job_size'),/Symbolic links/);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('execution lifecycle forces isolated cwd and records uploaded artifact ids',async()=>{const root=await fs.mkdtemp(path.join(tmpdir(),'qualyntra-agent-life-'));try{const manager=new AgentWorkspaceManager(root,1024,false);const uploads:any[]=[];const client={async uploadArtifact(input:any){uploads.push(input);return{id:'art_1'};}} as any;const lifecycle=new ExecutionAgentLifecycle(manager,[],client);const job:any={id:'job_life',runId:'r1',request:{runId:'r1',projectId:'p1',runtime:{language:'python',runner:'pytest'}},metadata:{correlationId:'c1'}};const request=await lifecycle.prepare(job);await fs.writeFile(path.join(request.cwd!,'result.xml'),'<x/>');const result=await lifecycle.afterResult(job,{runId:'r1',status:'passed',startedAt:'a',finishedAt:'b',resultFiles:['result.xml']});assert.equal(uploads.length,1);assert.deepEqual((result.metadata as any).artifactIds,['art_1']);assert.ok(request.cwd?.includes('job_life'));}finally{await fs.rm(root,{recursive:true,force:true});}});
