/**
 * File: adapters/integrations/github/src/index.ts
 * Purpose: Implements GitHub commit-status, issue, and comment integration through configurable REST endpoints and secret references.
 * Author: Raushan Raj
 */
import type { AdapterHealth,IntegrationAdapter,IntegrationRequest,IntegrationResponse,NetworkPolicy,SecretReference } from '../../../../packages/contracts/src';
import type { SecretResolverRegistry } from '../../../../packages/security/src/secrets';
import { assertNetworkAllowed } from '../../../../packages/security/src/network-policy';
import { asIntegrationRecord,FetchIntegrationHttpTransport,type IntegrationHttpTransport } from '../../../../packages/integrations/src/http';
import { dedupe,InMemoryIntegrationDedupeStore,type IntegrationDedupeStore } from '../../../../packages/integrations/src/dedupe';
import { withIntegrationRetry,type IntegrationRetryPolicy } from '../../../../packages/integrations/src/retry';
import { bearerHeader,encodeSegment,endpoint,normalizeStatus,optionalString,rateLimit,requiredNumber,requiredString } from '../../../../packages/integrations/src/utils';

export interface GitHubIntegrationOptions{id?:string;baseUrl:string;owner:string;repository:string;token:SecretReference;secrets:SecretResolverRegistry;networkPolicy:NetworkPolicy;transport?:IntegrationHttpTransport;timeoutMs?:number;headers?:Record<string,string>;apiVersion?:string;retryPolicy?:IntegrationRetryPolicy;dedupeStore?:IntegrationDedupeStore;}
export class GitHubIntegrationAdapter implements IntegrationAdapter{
  readonly descriptor;private readonly transport:IntegrationHttpTransport;private readonly dedupeStore:IntegrationDedupeStore;
  constructor(private readonly options:GitHubIntegrationOptions){this.descriptor={id:options.id??'github',kind:'integration' as const,version:'1.0.0',displayName:'GitHub',description:'GitHub commit status, issue, and comment integration',capabilities:['publish-status','create-work-item','comment'],supportedTools:['github']};this.transport=options.transport??new FetchIntegrationHttpTransport();this.dedupeStore=options.dedupeStore??new InMemoryIntegrationDedupeStore();}
  async health():Promise<AdapterHealth>{try{const url=endpoint(this.options.baseUrl,'/');assertNetworkAllowed(url,this.options.networkPolicy);return{status:'healthy',message:'configured; no remote health request performed',checkedAt:new Date().toISOString()};}catch(error){return{status:'unavailable',message:error instanceof Error?error.message:'invalid configuration',checkedAt:new Date().toISOString()};}}
  async execute(request:IntegrationRequest):Promise<IntegrationResponse>{switch(request.operation){case'publish-status':return this.publishStatus(request);case'create-work-item':return this.createIssue(request);case'comment':return this.comment(request);default:throw new Error(`GitHub integration does not support operation: ${request.operation}`);}}
  private async publishStatus(request:IntegrationRequest){const sha=requiredString(request.payload,'sha');const state=normalizeStatus(request.payload.state??request.payload.status);if(state==='cancelled'||state==='neutral')throw new Error(`GitHub commit status does not support state: ${state}`);const body={state,target_url:optionalString(request.payload,'targetUrl'),description:optionalString(request.payload,'description'),context:optionalString(request.payload,'context')??'qualyntra'};return this.post(request,`repos/${encodeSegment(this.options.owner)}/${encodeSegment(this.options.repository)}/statuses/${encodeSegment(sha)}`,body,request.idempotencyKey);}
  private async createIssue(request:IntegrationRequest){const title=requiredString(request.payload,'title');const body=optionalString(request.payload,'body');const labels=Array.isArray(request.payload.labels)?request.payload.labels.filter(v=>typeof v==='string'):undefined;const key=request.idempotencyKey;if(!key)throw new Error('GitHub create-work-item requires idempotencyKey to prevent duplicate issues');return this.post(request,`repos/${encodeSegment(this.options.owner)}/${encodeSegment(this.options.repository)}/issues`,{title,body,labels},key);}
  private async comment(request:IntegrationRequest){const issueNumber=requiredNumber(request.payload,'issueNumber');const body=requiredString(request.payload,'body');return this.post(request,`repos/${encodeSegment(this.options.owner)}/${encodeSegment(this.options.repository)}/issues/${issueNumber}/comments`,{body},request.idempotencyKey);}
  private async post(request:IntegrationRequest,path:string,body:unknown,dedupeKey?:string):Promise<IntegrationResponse>{const key=dedupeKey?`${this.descriptor.id}:${request.scope.organizationId}:${request.operation}:${dedupeKey}`:undefined;return dedupe(this.dedupeStore,key,async()=>withIntegrationRetry(async()=>{const url=endpoint(this.options.baseUrl,path);assertNetworkAllowed(url,this.options.networkPolicy);const headers:Record<string,string>={'accept':'application/vnd.github+json','content-type':'application/json','authorization':await bearerHeader(this.options.secrets,this.options.token),...this.options.headers};if(this.options.apiVersion)headers['x-github-api-version']=this.options.apiVersion;const response=await this.transport.request({adapterId:this.descriptor.id,url,method:'POST',headers,body:JSON.stringify(body),timeoutMs:this.options.timeoutMs});const value=asIntegrationRecord(response.body);return{ok:true,externalId:value.id===undefined?undefined:String(value.id),uri:typeof value.html_url==='string'?value.html_url:typeof value.url==='string'?value.url:undefined,requestId:response.headers['x-github-request-id']??response.headers['x-request-id'],rateLimit:rateLimit(response.headers),metadata:{status:response.status}};},{idempotent:Boolean(dedupeKey),policy:this.options.retryPolicy}));}
}
